tachyon/base/strings/string_util.h
tachyon/math/elliptic_curves/bls/bls12_381/BUILD.bazel
tachyon/math/elliptic_curves/bn/bn254/BUILD.bazel
tachyon/math/elliptic_curves/secp/secp256k1/BUILD.bazel
tachyon/math/elliptic_curves/short_weierstrass/affine_point_impl.h
tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_impl.h
tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h
tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h
tachyon/math/finite_fields/BUILD.bazel
tachyon/math/finite_fields/fp2.h
tachyon/math/finite_fields/fp2_forward.h
tachyon/math/finite_fields/generator/BUILD.bazel
tachyon/math/finite_fields/generator/build_defs.bzl
tachyon/math/finite_fields/generator/ext_prime_field_generator/BUILD.bazel
tachyon/math/finite_fields/generator/ext_prime_field_generator/build_defs.bzl
tachyon/math/finite_fields/generator/ext_prime_field_generator/ext_prime_field_generator.cc
tachyon/math/finite_fields/generator/generator.cc
tachyon/math/finite_fields/generator/prime_field_generator/BUILD.bazel
tachyon/math/finite_fields/generator/prime_field_generator/build_defs.bzl
tachyon/math/finite_fields/generator/prime_field_generator/prime_field_generator.cc
tachyon/math/finite_fields/goldilocks_prime/BUILD.bazel
tachyon/math/finite_fields/prime_field_base.h
tachyon/math/finite_fields/prime_field_correctness_test.cc
tachyon/math/finite_fields/prime_field_unittest.cc
tachyon/math/finite_fields/quadratic_extension_field.h
tachyon/math/finite_fields/quadratic_extension_field_traits.h
tachyon/math/finite_fields/quadratic_extension_field_unittest.cc
tachyon/math/finite_fields/test/BUILD.bazel

This PR implements `QuadraticExtensionField` initially.

feat: implement quad ext field

---

benchmark/msm/msm_config.cc
tachyon/base/bits.h
tachyon/base/memory/aligned_memory_unittest.cc
tachyon/base/numerics/math_constants.h
tachyon/base/ranges/algorithm.h
tachyon/base/time/time_unittest.cc
tachyon/crypto/hashes/sponge/poseidon/poseidon.h
tachyon/math/base/big_int.h
tachyon/math/base/field.h
tachyon/math/base/groups.h
tachyon/math/base/rings.h
tachyon/math/base/semigroups.h
tachyon/math/elliptic_curves/msm/kernels/bellman/bellman_msm_kernels.cu.h
tachyon/math/finite_fields/modulus.h
tachyon/math/finite_fields/prime_field_util.cc
tachyon/math/polynomials/multivariate/multivariate_polynomial_unittest.cc

Add some theoretical explanation to the files under `math/base`.

chore(math): add comments to math base files

---

tachyon/crypto/commitments/pedersen/pedersen.h
tachyon/crypto/hashes/sponge/poseidon/grain_lfsr.h
tachyon/crypto/hashes/sponge/poseidon/poseidon.h
tachyon/crypto/hashes/sponge/poseidon/poseidon_config.h

Add comments to `crypto` files:
- Pedersen commitment
- Poseidon Hash

chore(crypto): add comments to crypto

---

tachyon/base/buffer/buffer.h
tachyon/cc/math/finite_fields/prime_field_unittest.cc
tachyon/crypto/hashes/sponge/poseidon/poseidon_config.h
tachyon/math/elliptic_curves/msm/variable_base_msm.h
tachyon/math/finite_fields/prime_field.h
tachyon/math/finite_fields/prime_field_base.h
tachyon/math/geometry/point2.h
tachyon/math/geometry/point3.h
tachyon/math/geometry/point4.h
tachyon/math/matrix/sparse/sparse_matrix.h
tachyon/math/polynomials/multivariate/multivariate_polynomial.h
tachyon/math/polynomials/univariate/dense_coefficients.h
tachyon/math/polynomials/univariate/sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_polynomial.h

- Add a brief description to each logic in the `tachyon/math` directory.
- Run clang-format

chore(math): add math comments

---

.github/workflows/ci.yml

Modify cpplint script to run only for the changes in PR

ci: change cpplint script

---

tachyon/math/elliptic_curves/short_weierstrass/test/BUILD.bazel

Apply the changes that were supposed to be implemented along with #86.

fix(math): fix missing changes

---

Cargo.Bazel.lock
Cargo.lock
Cargo.toml
README.md
WORKSPACE
benchmark/README.md
benchmark/msm/BUILD.bazel
benchmark/msm/halo2/BUILD.bazel
benchmark/msm/halo2/Cargo.toml
benchmark/msm/halo2/src/lib.rs
benchmark/msm/msm_benchmark.cc
benchmark/msm/msm_config.cc
benchmark/msm/msm_config.h
benchmark/simple_benchmark_reporter.cc

Add Halo2 MSM benchmark on BN254.
See https://github.com/kroma-network/halo2

feat(benchmark): add halo2 msm benchmark

---

.gitmessage
LICENSE-APACHE.halo2
LICENSE-MIT.halo2
tachyon/zk/BUILD.bazel
tachyon/zk/value.h
tachyon/zk/value_unittest.cc

See https://github.com/zcash/halo2/blob/main/halo2_proofs/src/circuit/value.rs

feat(zk): implement `Value`

---

tachyon/math/base/big_int.h
tachyon/math/elliptic_curves/bn/bn254/BUILD.bazel
tachyon/math/finite_fields/BUILD.bazel
tachyon/math/finite_fields/cubic_extension_field.h
tachyon/math/finite_fields/cyclotomic_multiplicative_subgroup.h
tachyon/math/finite_fields/fp12.h
tachyon/math/finite_fields/fp12_unittest.cc
tachyon/math/finite_fields/fp2_unittest.cc
tachyon/math/finite_fields/fp6_unittest.cc
tachyon/math/finite_fields/generator/prime_field_generator/prime_field_generator.cc
tachyon/math/finite_fields/goldilocks_prime/prime_field_goldilocks.h
tachyon/math/finite_fields/quadratic_extension_field.h
tachyon/math/finite_fields/quadratic_extension_field_unittest.cc

This implements `CyclotomicMultiplicativeSubgroup`

feat: implement `CyclotomicMultiplicativeSubgroup`

---

tachyon/math/finite_fields/BUILD.bazel
tachyon/math/finite_fields/cubic_extension_field.h
tachyon/math/finite_fields/fp12.h
tachyon/math/finite_fields/fp2.h
tachyon/math/finite_fields/fp3.h
tachyon/math/finite_fields/fp4.h
tachyon/math/finite_fields/fp6.h
tachyon/math/finite_fields/generator/ext_prime_field_generator/ext_prime_field_generator.cc
tachyon/math/finite_fields/prime_field_base.h
tachyon/math/finite_fields/quadratic_extension_field.h

This implement https://en.wikipedia.org/wiki/Frobenius_endomorphism

feat: implement frobenius map

---

tachyon/math/polynomials/univariate/radix2_evaluation_domain.h

In PR #102, the `GetRootsOfUnity` function was made more generic for external use, but the issue of it still being private in terms of access was resolved.

feat(math): add missing changes abount pr #102

---

tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/univariate_dense_coefficients.h
tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc
tachyon/math/polynomials/univariate/univariate_evaluations.h
tachyon/math/polynomials/univariate/univariate_evaluations_unittest.cc
tachyon/math/polynomials/univariate/univariate_polynomial.h
tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc

The followings can be serialized after this PR.
- UnivariateTerm (before UnivariateSparse::Term)
- UnivariateDenseCoefficient, UnivariateSparseCoefficient
- UnivariateDensePolynomial, UnivariateSparsePolynomial
- UnivariatePolynomial

feat(math): impl copyable for univariate polynomials

---

tachyon/base/bits.h
tachyon/base/bits_unittest.cc
tachyon/math/polynomials/multivariate/BUILD.bazel
tachyon/math/polynomials/multivariate/multilinear_dense_evaluations.h
tachyon/math/polynomials/multivariate/multilinear_dense_evaluations_unittest.cc
tachyon/math/polynomials/multivariate/multilinear_extension.h
tachyon/math/polynomials/multivariate/multilinear_extension_ops.h
tachyon/math/polynomials/multivariate/multivariate_polynomial_unittest.cc
tachyon/math/polynomials/multivariate/support_poly_operators.h
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc
tachyon/math/polynomials/univariate/univariate_evaluation_domain_factory.h
tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc

This PR implements `MultilinearExtension`.

feat: implement multilinear extension

---

tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/assignment.h
tachyon/zk/plonk/circuit/circuit.h
tachyon/zk/plonk/circuit/layouter.h
tachyon/zk/plonk/circuit/region.h
tachyon/zk/plonk/circuit/region_shape.h
tachyon/zk/plonk/circuit/table.h
tachyon/zk/value.h

This PR prepares for [FloorPlanner](https://github.com/kroma-network/halo2/tree/dev/halo2_proofs/src/circuit/floor_planner).
This implements [Circuit](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/circuit.rs#L665-L687) and [Layouter](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/circuit.rs#L410-L494)

feat: prepare floor planner

---

.github/workflows/ci.yml

ci: fix python version

---

bazel/tachyon_deps.bzl
tachyon/math/base/BUILD.bazel
tachyon/math/base/big_int.h
tachyon/math/base/big_int_unittest.cc
tachyon/zk/transcript/BUILD.bazel
tachyon/zk/transcript/sha256_transcript.h
tachyon/zk/transcript/sha256_transcript_unittest.cc

This PR implements sha256 transcript.
See [ShaRead](https://github.com/kroma-network/halo2-snark-aggregator/blob/2637b512397b255525782006439a9cedde5b79b8/halo2-snark-aggregator-api/src/transcript/sha.rs#L14-L127) and [ShaWrite](https://github.com/kroma-network/halo2-snark-aggregator/blob/2637b512397b255525782006439a9cedde5b79b8/halo2-snark-aggregator-api/src/transcript/sha.rs#L129-L232).

feat(zk): implement sha256 transcript

---

tachyon/crypto/hashes/prime_field_serializable.h
tachyon/crypto/hashes/sponge/sponge.h
tachyon/device/gpu/gpu_info.h
tachyon/math/base/groups.h
tachyon/math/base/semigroups.h
tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/math/polynomials/univariate/univariate_dense_coefficients.h
tachyon/zk/plonk/constraint_system.h
tachyon/zk/plonk/permutation/permutation_assembly.h

This PR passes "parameter-only-types" by value not by reference!
See https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value/

perf: pass parameter only types by value

---

tachyon/math/polynomials/univariate/univariate_polynomial_ops.h
tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/assignment.h
tachyon/zk/plonk/circuit/cell.h
tachyon/zk/plonk/circuit/floor_planner/BUILD.bazel
tachyon/zk/plonk/circuit/floor_planner/simple_table_layouter.h
tachyon/zk/plonk/circuit/floor_planner/single_chip_layouter.h
tachyon/zk/plonk/circuit/layouter.h
tachyon/zk/plonk/circuit/region.h
tachyon/zk/plonk/circuit/region_shape.h

This PR implements [floor_planner/single_pass](https://github.com/kroma-network/halo2/blob/dev/halo2_proofs/src/circuit/floor_planner/single_pass.rs) which is an implementation of `FloorPlanner` based on #118 
`SimpleTableLayouter` and `SingleChipLayouter` are not clear to me so refactoring is not done at this moment.

feat(zk): implement `SingleChipLayouter`

---

tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/rotation.h

- implement RotateOmega() on UnivariateEvaluationDomain
* the function is used on LookupArgument and PermutationArgument.

feat(zk): implement `RotateOmega()`

---

tachyon/crypto/commitments/kzg/BUILD.bazel
tachyon/crypto/commitments/kzg/kzg.h
tachyon/crypto/commitments/kzg/kzg_unittest.cc
tachyon/crypto/commitments/pedersen/BUILD.bazel
tachyon/math/elliptic_curves/BUILD.bazel
tachyon/math/elliptic_curves/point_conversions.h
tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_dense_coefficients.h

- KZG Params
- `k`: Degree of the polynomial
- `n`: 2^k
- `g1_powers_of_tau`: [𝜏⁰g₁, 𝜏¹g₁, ... , 𝜏ⁿ⁻¹g₁]
- `g1_powers_of_tau_lagrange`: Bases multiplied by Lagrange coefficients of tau and g1
- `g2`: G2 Generator
- `tau_g2`:  𝜏g₂
- UnsafeSetup: Initialize parameters with a random toxic point.
- Commit: Commit to a polynomial with given coefficients.
- CommitLagrange: Commit to a polynomial with Lagrange coefficients.
This PR should be merged after #126

feat: implement KZG Params

---

tachyon/base/BUILD.bazel
tachyon/base/openmp_util.h
tachyon/base/parallelize.h
tachyon/base/parallelize_unittest.cc
tachyon/math/base/BUILD.bazel
tachyon/math/base/semigroups.h
tachyon/math/polynomials/multivariate/BUILD.bazel
tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/zk/plonk/permutation/BUILD.bazel
tachyon/zk/plonk/permutation/permutation_assembly.h

It provides a `Chunked Parallelize Loop` feature using OpenMP.

feat(base): add util for chunked parallelize loop

---

tachyon/crypto/commitments/kzg/BUILD.bazel
tachyon/crypto/commitments/kzg/kzg.h
tachyon/crypto/commitments/kzg/kzg_unittest.cc
tachyon/math/finite_fields/BUILD.bazel
tachyon/math/finite_fields/cubic_extension_field.h
tachyon/math/finite_fields/fp12_unittest.cc
tachyon/math/finite_fields/fp2_unittest.cc
tachyon/math/finite_fields/fp6_unittest.cc
tachyon/math/finite_fields/quadratic_extension_field.h

- Add Copyable for Quadratic Extension Field and Cubic Extension Field
- Add Copyable for KZGParams

feat: implement KZGParams copyable

---

tachyon/crypto/commitments/kzg/kzg_commitment_scheme.h

* fix `DoMsm()` on `KZGCommitmentScheme`

fix(crypto): fix `DoMsm()` on `KZGCommitmentScheme`

---

tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/math/polynomials/univariate/univariate_evaluation_domain_factory.h

- n = DegreeToSize(d) = d + 1
- d = SizeToDegree(n) = n - 1

fix(math): fix computing degree and size

---

tachyon/base/parallelize.h
tachyon/base/parallelize_unittest.cc
tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/univariate_dense_coefficients.h

This PR implements `ParallelizeMap` and `ParallelizeMapByChunkSize`.

feat: implement parallelize map

---

tachyon/zk/plonk/BUILD.bazel
tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/expressions/BUILD.bazel
tachyon/zk/plonk/circuit/expressions/evaluator/BUILD.bazel
tachyon/zk/plonk/circuit/expressions/evaluator/selector_replacer.h
tachyon/zk/plonk/circuit/expressions/evaluator/selector_replacer_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/simple_evaluator_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_extractor_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_finder_unittest.cc
tachyon/zk/plonk/circuit/expressions/expression.h
tachyon/zk/plonk/circuit/expressions/expression_factory.h
tachyon/zk/plonk/circuit/selector_compressor.h
tachyon/zk/plonk/constraint_system.h
tachyon/zk/plonk/keys/verifying_key.h

This PR implements selector compression and almost completes verification key generation hopefully. Should be merged after #136 
I'll add unittests later!

feat(zk): implement gen vkey

---

tachyon/math/polynomials/multivariate/multilinear_dense_evaluations.h
tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_dense_coefficients.h
tachyon/math/polynomials/univariate/univariate_evaluations.h
tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h
tachyon/zk/base/BUILD.bazel
tachyon/zk/base/blinder.h
tachyon/zk/base/blinder_unittest.cc
tachyon/zk/base/random_field_generator.h

This implements `Blinder` interface to be used by Halo2.

feat(zk): implement blinder

---

tachyon/base/containers/container_util.h
tachyon/base/containers/container_util_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator.h
tachyon/zk/plonk/circuit/expressions/evaluator/BUILD.bazel
tachyon/zk/plonk/circuit/expressions/evaluator/calculation.cc
tachyon/zk/plonk/circuit/expressions/evaluator/calculation.h
tachyon/zk/plonk/circuit/expressions/evaluator/cl_evaluator.h
tachyon/zk/plonk/circuit/expressions/evaluator/graph_evaluator.h
tachyon/zk/plonk/circuit/expressions/evaluator/graph_evaluator_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/selector_replacer.h
tachyon/zk/plonk/circuit/expressions/evaluator/selector_replacer_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/simple_evaluator.h
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_extractor.h
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_extractor_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_finder.h
tachyon/zk/plonk/circuit/expressions/evaluator/simple_selector_finder_unittest.cc
tachyon/zk/plonk/circuit/expressions/evaluator/value_source.cc
tachyon/zk/plonk/circuit/expressions/evaluator/value_source.h
tachyon/zk/plonk/circuit/expressions/evaluator/value_source_data.h
tachyon/zk/plonk/circuit/expressions/evaluator/value_source_unittest.cc
tachyon/zk/plonk/circuit/expressions/expression.h
tachyon/zk/plonk/circuit/floor_planner/single_chip_layouter.h
tachyon/zk/plonk/circuit/virtual_cells.h
tachyon/zk/plonk/constraint_system.h
tachyon/zk/plonk/keys/BUILD.bazel
tachyon/zk/plonk/keys/proving_key.h
tachyon/zk/plonk/keys/proving_key_unittest.cc
tachyon/zk/plonk/permutation/permutation_assembly.h

This PR prepares proving key generation.

feat(zk): prepare gen pkey

---

.github/workflows/ci.yml

Add Node binding test and Python binding test for both Linux and MacOS.

ci: add node binding and py binding test

---

README.md

This PR updates main README.md for devconnect event. There will be a couple of visitors during the event and we want to clarify what it is for.

docs: add simple introduction and design goals to README

---

README.md

#165 was merged quickly and I didn't give much time to be reviewed by teammates. 
This is suggested by @seohoyoon93

docs: update design goals precisely

---

tachyon/math/base/groups.h
tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/lagrange_interpolation.h
tachyon/math/polynomials/univariate/lagrange_interpolation_unittest.cc

The Lagrange interpolating polynomial is the unique polynomial of lowest degree that interpolates a given set of points.
See https://en.wikipedia.org/wiki/Lagrange_polynomial

feat(math): implement lagrange interpolation

---

tachyon/zk/base/halo2_prover.h
tachyon/zk/base/halo2_prover_test.h
tachyon/zk/base/prover.h
tachyon/zk/plonk/lookup/lookup_permuted.h
tachyon/zk/plonk/permutation/grand_product_argument.h
tachyon/zk/plonk/permutation/permutation_argument.h

This PR adds a new member `extended_domain_` to `Prover`.

feat(zk): add `extended_domain_` to `Prover`

---

tachyon/zk/base/BUILD.bazel
tachyon/zk/base/entity.h
tachyon/zk/base/halo2_prover.h
tachyon/zk/base/prover.h
tachyon/zk/base/verifier.h
tachyon/zk/plonk/lookup/lookup_argument.h
tachyon/zk/plonk/lookup/lookup_committed.h
tachyon/zk/plonk/lookup/lookup_evaluated.h
tachyon/zk/plonk/lookup/permute_expression_pair.h
tachyon/zk/plonk/permutation/permutation_argument_unittest.cc
tachyon/zk/plonk/permutation/permutation_assembly.h
tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc
tachyon/zk/plonk/permutation/permutation_committed.h
tachyon/zk/plonk/permutation/permutation_evaluated.h

This PR creates `Verifier` class which is opposite to `Prover`. This class will be used when implementing verification and some of codes that can be called from a verifier side, are changed within this PR.

refac(zk): create verifier

---

tachyon/zk/plonk/BUILD.bazel
tachyon/zk/plonk/circuit/phase.h
tachyon/zk/plonk/circuit/table_unittest.cc
tachyon/zk/plonk/constraint_system.h
tachyon/zk/plonk/constraint_system_unittest.cc

This PR fixes bug of `ConstraintSystem` while adding a unittest for it.

fix(zk): fix bug on constraint system

---

tachyon/crypto/commitments/kzg/shplonk.h

Those lines are used for debugging and should be removed in production.

fix(crypto): fix redundant check

---

LICENSE.lambdaworks
tachyon/base/buffer/buffer.h
tachyon/base/buffer/string_buffer.h
tachyon/base/buffer/vector_buffer.h
tachyon/crypto/commitments/kzg/kzg_unittest.cc
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/BUILD.bazel
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_hasher.h
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_proof.h
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree.h
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree_storage.h
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree_unittest.cc
tachyon/crypto/commitments/pedersen/pedersen_unittest.cc
tachyon/math/base/big_int_unittest.cc
tachyon/math/elliptic_curves/affine_point_unittest.cc
tachyon/math/elliptic_curves/jacobian_point_unittest.cc
tachyon/math/elliptic_curves/point_xyzz_unittest.cc
tachyon/math/elliptic_curves/projective_point_unittest.cc
tachyon/math/finite_fields/fp12_unittest.cc
tachyon/math/finite_fields/fp2_unittest.cc
tachyon/math/finite_fields/fp6_unittest.cc
tachyon/math/finite_fields/prime_field_unittest.cc
tachyon/math/geometry/point2_unittest.cc
tachyon/math/geometry/point3_unittest.cc
tachyon/math/geometry/point4_unittest.cc
tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc
tachyon/math/polynomials/univariate/univariate_evaluations_unittest.cc
tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc
tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc
tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc

This PR adds `BinaryMerkleTree` which is needed by `FRICommitment`.

feat(crypto): add binary merkle tree

---

tachyon/math/base/groups.h

This reverts commit 288564adc7d1ee34fe0c6d3ebca511318ff9c6c6.

fix(math): fix batch inverse bug on parallel

---

tachyon/zk/plonk/circuit/rotation.h

TODO: I think we don't need even multplying x if we can create domain using `Coset()` once we get the x.

refac(zk): replace `RotateOmega()` with `GetElement()`

---

tachyon/crypto/commitments/BUILD.bazel
tachyon/crypto/commitments/kzg/shplonk.h
tachyon/crypto/commitments/polynomial_openings.h
tachyon/crypto/commitments/polynomial_openings_unittest.cc

When me seeing #211, it's very confusing me because notation used by creating opening proof part and verification part is different. This PR solves this problem by updating comment to use same notation between them.

refac(crypto): refactor shplonk for better readability

---

bazel/tachyon_deps.bzl
tachyon/base/json/BUILD.bazel
tachyon/base/json/json.h
tachyon/base/json/json_unittest.cc
tachyon/base/json/rapidjson_util.cc
tachyon/base/json/rapidjson_util.h
tachyon/base/json/test/simple_data.json
third_party/rapidjson/rapidjson.BUILD

This PR implements JSON serialization and deserialization initially. There are various JSON implementation out there. The reason I chose `RapidJSON` is just I am familiar with this and it doesn't throw an exception unlike https://github.com/nlohmann/json.

feat(base): add json utility initially

---

tachyon/crypto/commitments/fri/fri.h
tachyon/crypto/commitments/kzg/shplonk.h
tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree.h
tachyon/crypto/commitments/pedersen/pedersen.h
tachyon/crypto/hashes/sponge/poseidon/poseidon.h
tachyon/crypto/random/xor_shift/xor_shift_rng.h
tachyon/zk/base/commitments/shplonk_extension.h
tachyon/zk/plonk/halo2/poseidon_sponge.h

This PR added `final` keyword to the most derived classes.

refac: add `final` keyword to the most derived class

---

tachyon/crypto/commitments/kzg/shplonk.h
tachyon/math/elliptic_curves/pairing/pairing_unittest.cc

This PR optimizes codes a little bit.

perf: optimize minor codes

---

tachyon/math/base/semigroups.h
tachyon/math/polynomials/univariate/univariate_evaluation_domain.h

This PR implements 2 methods.
- `GetSuccessivePowers()`
- `GetSuccessiveScalarMuls()`
Additionally, `GetSuccessivePowers()` gets improved by accepting 1 more parameter.

feat(math): improve get successive methods

---

tachyon/base/template_util.h
tachyon/crypto/commitments/kzg/shplonk.h
tachyon/math/base/BUILD.bazel
tachyon/math/base/rational_field.h
tachyon/math/elliptic_curves/BUILD.bazel
tachyon/math/elliptic_curves/pairing/BUILD.bazel
tachyon/math/elliptic_curves/pairing/pairing.h
tachyon/math/elliptic_curves/point_conversions.h
tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/lagrange_interpolation.h
tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/table_base.h

This PR optimizes `SHPlonk` verification by creating `G2Prepared` in advance and calling `Pairing()` just once.

perf: optimize shplonk verification

---

tachyon/base/containers/container_util.h
tachyon/math/polynomials/univariate/univariate_polynomial_ops.h
tachyon/zk/r1cs/BUILD.bazel
tachyon/zk/r1cs/linear_combination.h
tachyon/zk/r1cs/linear_combination_unittest.cc
tachyon/zk/r1cs/term.h
tachyon/zk/r1cs/variable.cc
tachyon/zk/r1cs/variable.h
tachyon/zk/r1cs/variable_unittest.cc

This PR implements [LinearCombination](https://github.com/arkworks-rs/snark/blob/0759f942e18eb73fc2b5da2ee58d2994d3dc557d/relations/src/r1cs/impl_lc.rs) which is going to be used by R1CS.

feat: implement linear combination

---

tachyon/math/polynomials/multivariate/multivariate_polynomial_unittest.cc
tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h
tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc
tachyon/zk/r1cs/BUILD.bazel
tachyon/zk/r1cs/constraint_matrices.h
tachyon/zk/r1cs/constraint_system.h
tachyon/zk/r1cs/constraint_system_unittest.cc
tachyon/zk/r1cs/linear_combination.h
tachyon/zk/r1cs/linear_combination_unittest.cc
tachyon/zk/r1cs/matrix.h
tachyon/zk/r1cs/optimization_goal.h
tachyon/zk/r1cs/synthesis_mode.h
tachyon/zk/r1cs/variable.h

This PR implements [R1CS Constraint System](https://github.com/arkworks-rs/snark/blob/0759f942e18eb73fc2b5da2ee58d2994d3dc557d/relations/src/r1cs/constraint_system.rs).

feat(zk): implement r1cs constraint system

---

tachyon/zk/plonk/circuit/BUILD.bazel
tachyon/zk/plonk/circuit/floor_planner/BUILD.bazel
tachyon/zk/plonk/circuit/floor_planner/lookup_table_assigner.h
tachyon/zk/plonk/circuit/floor_planner/plan_region.h
tachyon/zk/plonk/circuit/floor_planner/single_chip_layouter.h
tachyon/zk/plonk/circuit/floor_planner/v1/BUILD.bazel
tachyon/zk/plonk/circuit/floor_planner/v1/assignment_pass.h
tachyon/zk/plonk/circuit/floor_planner/v1/v1_plan.h
tachyon/zk/plonk/circuit/region.h
tachyon/zk/plonk/circuit/region_layouter.h
tachyon/zk/plonk/circuit/region_shape.h

- Rename `V1Pass` to `V1Layouter`.
- Add `RegionLayouter` class and replace duplicate code.
- Add `LookupTableAssigner` class and replace duplicate code.

refac(zk): refactor floor planner

---

tachyon/math/base/semigroups.h
tachyon/math/elliptic_curves/msm/test/msm_test_set.h
tachyon/zk/expressions/expression.h
tachyon/zk/plonk/circuit/floor_planner/floor_planner.h
tachyon/zk/plonk/circuit/floor_planner/simple_floor_planner.h
tachyon/zk/plonk/circuit/floor_planner/v1/v1_floor_planner.h
tachyon/zk/plonk/constraint_system.h
tachyon/zk/plonk/halo2/synthesizer.h
tachyon/zk/plonk/keys/key.h
tachyon/zk/plonk/keys/proving_key.h
tachyon/zk/plonk/keys/verifying_key.h

This PR changes function argument type `Circuit&` to `const Circuit&`.

refac(zk): change circuit to const reference

---

.github/workflows/ci.yml
bazel/buildifier_deps.bzl
tachyon/base/threading/BUILD.bazel
tachyon/base/time/time_buildflags.bzl
tachyon/c/BUILD.bazel
tachyon/cc/BUILD.bazel
tachyon/math/base/BUILD.bazel
tachyon/math/elliptic_curves/bls12/bls12_381/BUILD.bazel
tachyon/math/elliptic_curves/bn/bn254/BUILD.bazel
tachyon/math/finite_fields/test/BUILD.bazel
tachyon/node/test/src/base/test/BUILD.bazel
tachyon/node/test/src/math/elliptic_curves/short_weierstrass/BUILD.bazel
tachyon/node/test/src/math/finite_fields/BUILD.bazel
vendors/halo2/BUILD.bazel

This PR bumps up buildifier to 6.4.0 and runs buildifier

build: bump buildifier to 6.4.0

---

tachyon/base/openmp_util.h
tachyon/math/polynomials/univariate/BUILD.bazel
tachyon/math/polynomials/univariate/lagrange_interpolation.h
tachyon/math/polynomials/univariate/lagrange_interpolation_unittest.cc

This PR fixes the bug related to openmp.

fix: correct parallel computation

---

tachyon/c/math/polynomials/constants.h
tachyon/c/zk/plonk/halo2/bn254_shplonk_prover.cc
tachyon/c/zk/plonk/halo2/bn254_shplonk_prover.h
tachyon/c/zk/plonk/halo2/prover_impl_base.h
tachyon/c/zk/plonk/halo2/prover_replay.cc
tachyon/crypto/commitments/kzg/BUILD.bazel
tachyon/crypto/commitments/kzg/kzg_family.h
tachyon/crypto/commitments/kzg/shplonk.h
tachyon/crypto/commitments/kzg/shplonk_unittest.cc
tachyon/zk/base/commitments/shplonk_extension.h

This PR enables logging PCS params. This help us reducing time-consuming unsafe setup.

feat: enable logging pcs params

---

tachyon/zk/plonk/vanishing/circuit_polynomial_builder.h

In this PR, the calls to base::Parallelize() that were happening within `UpdateValuesByCustomGates`, `UpdateValuesByPermutation`, and `UpdateValuesByLookups` have been modified to occur just once from the caller.
This PR does not result in any current performance changes, but it has improved code readability and made it easier to optimize parallelization in the future.

perf(zk): merge parallelized parts

---

tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc

The test degree was too low to test the parallel part of IFFT. This PR reinforces IFFT test by increasing the degree.

test(math): reinforce test for parallel IFFT

---

tachyon/base/buffer/BUILD.bazel
tachyon/base/buffer/copyable.h
tachyon/c/math/elliptic_curves/msm/msm_gpu.h
tachyon/c/math/elliptic_curves/msm/msm_gpu_replay.cc

This fixes broken build occurring at #277

fix: fix broken build with cuda

---

.github/workflows/ci.yml
tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc

By using constants, we can achieve better test code maintenance.

test(math): refac test parameter init for `FFTCorrectness` test

---

vendors/halo2/src/bn254_gwc_prover.cc
vendors/halo2/src/bn254_shplonk_prover.cc
vendors/halo2/src/circuits/mod.rs
vendors/halo2/src/circuits/shuffle_circuit.rs
vendors/halo2/src/circuits/simple_circuit.rs
vendors/halo2/src/circuits/simple_lookup_circuit.rs

This PR adds shuffle circuit test to test multi phase.

test: add shuffle circuit test

---

tachyon/math/base/rational_field.h

This PR optimizes `RationalField<F>::BatchEvaluate` by merging 3 parallel loops into one.

perf(math): optimize `RationalField<F>::BatchEvaluate()`

---

tachyon/zk/plonk/vanishing/vanishing_utils.h

This PR merges two parallel loops into one.

perf(zk): optimize divide by vanishing poly inplace

---

tachyon/math/polynomials/univariate/lagrange_interpolation.h

This PR optimizes `LagrangeInterpolate()` by parallelizing the outer loop instead of the inner loop.

perf(math): optimize `LagrangeInterpolate`

---

tachyon/crypto/commitments/BUILD.bazel
tachyon/crypto/commitments/polynomial_openings.h
tachyon/math/polynomials/univariate/univariate_polynomial.h

Add parallelization for `CombineLowDegreeExtensions` and `EvaluateVanishingPolyByRootsSerial`.

perf: optimize SHPlonk

---

tachyon/crypto/sumcheck/BUILD.bazel
tachyon/crypto/sumcheck/sumcheck_proving_key.h
tachyon/crypto/sumcheck/sumcheck_proving_key_unittest.cc
tachyon/crypto/sumcheck/sumcheck_verifying_key.h
tachyon/crypto/sumcheck/sumcheck_verifying_key_unittest.cc
tachyon/math/polynomials/multivariate/BUILD.bazel
tachyon/math/polynomials/multivariate/linear_combination.h
tachyon/math/polynomials/multivariate/linear_combination_term.h
tachyon/math/polynomials/multivariate/linear_combination_unittest.cc
tachyon/math/polynomials/multivariate/multilinear_dense_evaluations.h
tachyon/math/polynomials/multivariate/multilinear_extension.h

- Adds LinearCombination data structure
- Adds VerifyingKey/ProvingKey
- Tests data structures
Note: logic regarding num_variables and related checks is not finalized
Referenced [arkworks' sumcheck code](https://github.com/arkworks-rs/sumcheck/blob/master/src/ml_sumcheck/data_structures.rs)

feat: implement multilinear sumcheck data structures

---

tachyon/zk/plonk/vanishing/vanishing_argument.h

This PR avoids copying data by returning the reference.

perf(zk): avoid copying data

---

tachyon/zk/plonk/halo2/optimizations.md

This PR adds a document which contains a list of optimizations that have been made to the [scroll/halo2](https://github.com/scroll-tech/halo2) codebase.

docs: add docs for halo2 optimizations

---

docs/development/conventions.md
tachyon/base/numerics/README.md

fixing sentence structures and minor issues in the docs

chore: cleanup docs

---

README.md
tachyon/math/elliptic_curves/pairing/pairing_unittest.cc
tachyon/zk/r1cs/constraint_system/BUILD.bazel
tachyon/zk/r1cs/constraint_system/circuit.h
tachyon/zk/r1cs/constraint_system/constraint_system.h
tachyon/zk/r1cs/constraint_system/constraint_system_unittest.cc
tachyon/zk/r1cs/constraint_system/matrix.h
tachyon/zk/r1cs/constraint_system/quadratic_arithmetic_program.h
tachyon/zk/r1cs/constraint_system/test/BUILD.bazel
tachyon/zk/r1cs/constraint_system/test/simple_circuit.h
tachyon/zk/r1cs/groth16/BUILD.bazel
tachyon/zk/r1cs/groth16/groth16_unittest.cc
tachyon/zk/r1cs/groth16/key.h
tachyon/zk/r1cs/groth16/prepared_verifying_key.h
tachyon/zk/r1cs/groth16/proof.h
tachyon/zk/r1cs/groth16/prove.h
tachyon/zk/r1cs/groth16/proving_key.h
tachyon/zk/r1cs/groth16/toxic_waste.h
tachyon/zk/r1cs/groth16/verify.h
tachyon/zk/r1cs/groth16/verifying_key.h

This PR implements [groth16 proving scheme](https://eprint.iacr.org/2016/260.pdf). Please refer to https://github.com/arkworks-rs/groth16, too!

feat: implement groth16

---

tachyon/c/zk/plonk/halo2/BUILD.bazel
tachyon/c/zk/plonk/halo2/bn254_gwc_prover_unittest.cc

This PR enables the `GWCProver` C API.

fix(c): activate gwc prover

---

.github/workflows/ci.yml

Change MacOS runner from `macos-latest`(x86_64) to `macos-latest-xlarge`(arm64).

ci: change macos runner from x86_64 to arm64

---

docs/how_to_contribute/math/how_to_add_elliptic_curves.md

Fix typo in how_to_add_elliptic_curves.md

docs: fix typo in how_to_add_elliptic_curves.md

---

README.md
docs/how_to_contribute/math/how_to_add_prime_fields.md

- Add `Mersenne-31` and `Pasta` curves in README.md
- Add detailed explanation of prime field generator properties

docs: add prime field details

---

benchmark/README.md
tachyon/base/containers/circular_deque.h
tachyon/base/files/file.h

chore: fix typos

---

Dockerfile.base.jammy
Dockerfile.halo2.jammy

This PR adds the tachyon docker file.

build: add tachyon docker file

---

bazel/tachyon.bzl

This PR updates the Tachyon version to 0.0.1!

bulid: set tachyon version to 0.1.0

---

.github/workflows/ci.yml

Add option that tests with optimized build.
This PR should be merged after #374.

ci: add opt option to ci test

---

.github/workflows/ci.yml

Update setup-python action version to v5.

ci: use setup-python v5

---

tachyon/math/elliptic_curves/short_weierstrass/affine_point_impl.h
tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_impl.h
tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h
tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h
tachyon/math/finite_fields/fp6.h

This PR
1. Removes single-use variables in favor for in place functions.
2. Implements a more streamlined version of some logic

perf(math): streamline operations

---

tachyon/math/finite_fields/goldilocks/BUILD.bazel
tachyon/math/finite_fields/goldilocks/goldilocks_prime_field.h

This PR updates build configurations for x86 goldilocks.

build(math): update build settings for goldilocks

---

BUILD.bazel
bazel/tachyon_cc.bzl
docs/how_to_use/how_to_build.md

This PR adds a build flag to support building with Intel OpenMP.

build: add intel openmp support

---

docs/how_to_use/how_to_build.md

Add zip to Ubuntu prerequisites for building doxygen.

docs: add zip to Ubuntu prerequisites

---

tachyon/crypto/hashes/BUILD.bazel
tachyon/crypto/hashes/compressor.h
tachyon/crypto/hashes/hasher.h
tachyon/crypto/hashes/sponge/BUILD.bazel
tachyon/crypto/hashes/sponge/padding_free_sponge.h
tachyon/crypto/hashes/sponge/padding_free_sponge_unittest.cc
tachyon/crypto/hashes/sponge/poseidon/poseidon_grain_lfsr.h
tachyon/crypto/hashes/sponge/poseidon2/BUILD.bazel
tachyon/crypto/hashes/sponge/poseidon2/poseidon2.h
tachyon/crypto/hashes/sponge/poseidon2/poseidon2_config.h
tachyon/crypto/hashes/sponge/poseidon2/poseidon2_horizen_internal_matrix.h
tachyon/crypto/hashes/sponge/poseidon2/poseidon2_internal_matrix_unittest.cc
tachyon/crypto/hashes/sponge/poseidon2/poseidon2_plonky3_internal_matrix.h
tachyon/crypto/hashes/sponge/poseidon2/poseidon2_unittest.cc
tachyon/crypto/hashes/sponge/sponge.h
tachyon/crypto/hashes/sponge/truncated_permutation.h
tachyon/crypto/hashes/sponge/truncated_permutation_unittest.cc
tachyon/math/elliptic_curves/bls12/bls12_381/poseidon2.h
tachyon/math/elliptic_curves/bn/bn254/poseidon2.h
tachyon/math/elliptic_curves/pasta/pallas/poseidon2.h
tachyon/math/elliptic_curves/pasta/vesta/poseidon2.h
tachyon/math/finite_fields/baby_bear/BUILD.bazel
tachyon/math/finite_fields/baby_bear/poseidon2.h
tachyon/math/finite_fields/goldilocks/poseidon2.h
tachyon/math/finite_fields/koala_bear/BUILD.bazel
tachyon/math/finite_fields/koala_bear/poseidon2.h
tachyon/math/finite_fields/mersenne31/BUILD.bazel
tachyon/math/finite_fields/mersenne31/poseidon2.h
tachyon/zk/plonk/halo2/prime_field_conversion.h

This PR implements [PaddingFreeSponge](https://github.com/Plonky3/Plonky3/blob/fde81db95b8eeb39e07890f4099a7d59daeec52f/symmetric/src/sponge.rs#L10-L44) and [TruncatedPermutation](https://github.com/Plonky3/Plonky3/blob/fde81db95b8eeb39e07890f4099a7d59daeec52f/symmetric/src/compression.rs#L6-L44). Both of them are needed to test [mmcs](https://github.com/Plonky3/Plonky3/blob/fde81db95b8eeb39e07890f4099a7d59daeec52f/merkle-tree/src/mmcs.rs#L188-L223). See https://github.com/Plonky3/Plonky3/blob/fde81db95b8eeb39e07890f4099a7d59daeec52f/merkle-tree/src/mmcs.rs#L183-L184

feat: implement hash wrappers

---

tachyon/base/containers/container_util.h
tachyon/base/containers/container_util_unittest.cc
tachyon/zk/lookup/log_derivative_halo2/prover.h
tachyon/zk/lookup/log_derivative_halo2/prover_impl.h
tachyon/zk/plonk/permutation/grand_product_argument.h

This optimizes Log Derivative Halo2 proving in various aspects.

perf(zk): optimize log derivative halo2 lookup

---

vendors/circom/README.md

Since https://github.com/kroma-network/tachyon/pull/434 was introduced, the Circom README has been updated accordingly.

docs: update circom README.md

---

tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/math/polynomials/univariate/univariate_evaluation_domain.h

This PR optimizes the `DoFFT` function by decreasing unnecessary swap operations as much as possible.

perf: optimize fft

---

tachyon/math/base/semigroups.h
tachyon/math/finite_fields/cubic_extension_field.h
tachyon/math/finite_fields/prime_field_base.h
tachyon/math/finite_fields/quadratic_extension_field.h
tachyon/math/finite_fields/quartic_extension_field.h
tachyon/math/matrix/matrix_utils.h
tachyon/math/matrix/matrix_utils_unittest.cc
tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
tachyon/zk/air/plonky3/base/BUILD.bazel
tachyon/zk/air/plonky3/base/lagrange_selectors.h
tachyon/zk/air/plonky3/base/two_adic_multiplicative_coset.h
tachyon/zk/air/plonky3/base/two_adic_multiplicative_coset_unittest.cc

This PR implements [Plonky3's](https://github.com/kroma-network/Plonky3) [TwoAdicMultiplicativeCoset](https://github.com/kroma-network/Plonky3/blob/3b5265f9d5af36534a46caebf0617595cfb42c5a/commit/src/domain.rs#L58-L172) in preparation for Sp1

feat: impl two adic multiplicative coset

---

.github/workflows/ci.yml
tachyon/zk/air/constraint_system/BUILD.bazel
tachyon/zk/air/constraint_system/constraint_system.h
tachyon/zk/air/constraint_system/constraint_system_unittest.cc
tachyon/zk/air/constraint_system/variable.h
tachyon/zk/air/expressions/BUILD.bazel
tachyon/zk/air/expressions/air_evaluator.h
tachyon/zk/air/expressions/expression_factory.h
tachyon/zk/air/expressions/first_row_expression.h
tachyon/zk/air/expressions/last_row_expression.h
tachyon/zk/air/expressions/transition_expression.h
tachyon/zk/air/expressions/variable_expression.h
tachyon/zk/expressions/expression.h
tachyon/zk/expressions/expression_type.cc
tachyon/zk/expressions/expression_type.h
tachyon/zk/lookup/proving_evaluator.h
tachyon/zk/lookup/verifying_evaluator.h
tachyon/zk/plonk/expressions/evaluator/identifier.h
tachyon/zk/plonk/expressions/evaluator/selector_replacer.h
tachyon/zk/plonk/expressions/evaluator/simple_selector_extractor.h
tachyon/zk/plonk/expressions/evaluator/simple_selector_finder.h
tachyon/zk/plonk/halo2/stringifiers/expression_stringifier.h
tachyon/zk/plonk/vanishing/graph_evaluator.h

This PR implements the Plonky3 AIR constraint system.

feat(zk): implement air constraint system

---

README.md

This PR relocates Join Our Developer Community section in README for better visibility so developers can see our telegram group chat link better.

docs: update README for better visibility

---

tachyon/c/zk/plonk/halo2/buffer_reader.h
vendors/halo2/src/prover.rs

This fixes bugs while generating a scroll zkEVM proof.

fix: enable halo2 proof generation

---

vendors/circom/README.md
vendors/circom/prover_main.cc

This PR adds missing change from #490.

docs(circom): add missing change from #490

---

tachyon/math/polynomials/univariate/icicle/icicle_ntt.h

This PR fixes the cuda build that is currently failing on the main branch.

build: fix cuda build

---

tachyon/base/openmp_util.h
tachyon/math/finite_fields/baby_bear/packed_baby_bear_avx512.cc
tachyon/math/finite_fields/koala_bear/packed_koala_bear_avx512.cc
tachyon/math/finite_fields/mersenne31/packed_mersenne31_avx512.cc

This issue was raised in the Tachyon Discussion group chat. This PR fixes errors that occurred when testing with the Dockerfile below.
```dockerfile
FROM python:3.10
RUN apt-get update && apt-get upgrade -y
RUN apt-get update && \
apt install -y  pkg-config gnupg libssl-dev libgmp-dev libsodium-dev python3 python3-pip zip git awscli gcc nodejs npm
RUN npm install -g n
RUN n 18
RUN npm install -g yarn snarkjs
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install numpy
RUN git clone https://github.com/zkemail/email-wallet.git
WORKDIR /email-wallet/packages/prover
RUN pip install -r requirements.txt
RUN cp ./circom_proofgen.sh /root
WORKDIR /root
RUN mkdir params
WORKDIR /root/params
RUN gdown "https://drive.google.com/uc?id=1T1VvuaZhm1pSQoUkjaZptRbjq1XX8aT8"
RUN unzip params.zip …
```

build: support building tachyon based on python 3.10 docker image

---

.bazelrc
benchmark/ec/ec_double_benchmark_gpu.cc
tachyon/c/zk/plonk/halo2/kzg_family_prover_impl.h
tachyon/crypto/commitments/kzg/BUILD.bazel
tachyon/crypto/commitments/kzg/kzg.h
tachyon/device/gpu/gpu_memory.h
tachyon/device/gpu/gpu_memory_unittest.cc
tachyon/math/elliptic_curves/msm/algorithms/icicle/BUILD.bazel
tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm.h
tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bls12_381_g1.cc
tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bls12_381_g2.cc
tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bn254_g1.cc
tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bn254_g2.cc
tachyon/math/elliptic_curves/msm/variable_base_msm_gpu.h
tachyon/math/elliptic_curves/short_weierstrass/affine_point_correctness_gpu_test.cc
tachyon/math/elliptic_curves/short_weierstrass/non_affine_point_correctness_gpu_test.cc
tachyon/math/finite_fields/prime_field_correctness_gpu_test.cc
tachyon/math/finite_fields/prime_field_gpu_unittest.cc
tachyon/zk/base/commitments/gwc_extension.h
tachyon/zk/base/commitments/shplonk_extension.h
tachyon/zk/plonk/examples/BUILD.bazel
tachyon/zk/plonk/examples/fibonacci/BUILD.bazel

This PR is a performance improvement that allows the base to be recycled after initial allocation without reallocating when using MSM GPU in kzg commitment scheme.

perf: optimize msm gpu memory usage

---

docs/doxygen/Doxyfile.in
docs/how_to_contribute/conventions.md
docs/how_to_contribute/math/how_to_add_prime_fields.md

Hello
I found and fixed several spelling issues.
Br, Elias.

Fix spelling issues

---

.bazelrc
.github/workflows/ci.yml
README.md
benchmark/BUILD.bazel
benchmark/fft/README.md
benchmark/fft_batch/README.md
benchmark/fri/README.md
benchmark/msm/README.md
benchmark/poseidon/README.md
benchmark/poseidon2/README.md
docker/Dockerfile.halo2.jammy
docs/how_to_use/how_to_build.md
tachyon/node/test/.bazelrc
tachyon/node/test/README.md
tachyon/py/test/.bazelrc
vendors/circom/.bazelrc
vendors/circom/README.md
vendors/circom/circomlib/build/BUILD.bazel

In this PR, we add some compiler flags for improved performance at the cost of portability.

perf: add optimization flags

---

vendors/circom/circomlib/build/compile_witness_generator.sh

This PR fixes unhandled case in #557 :(

fix(circom): handle case when parts dont exist
