tachyon/math/base/bit_iterator.h, tachyon/math/base/bit_iterator_unittest.cc, tachyon/math/polynomials/univariate/sparse_polynomial_unittest.cc
While implementing Radix2 Evaluation Domain, test for evaluation on vanishing polynomials could not pass. Especially, cases with degree 1 polynomials were a problem.
@chokobole helped out fixing a bug in BitIterator in the case of little endian.
Unit test for sparse polynomial was missing a case with degree 1 polynomial, so I added one. Plus, I added another case with a polynomial with a degree 1 term.
=> fix(math): fix bit iteration in case of little endian

tachyon/c/BUILD.bazel
#52 moves MSM / MSM implementations into each curve generated msm files. Therefore, `libtachyon.so` should depend on this!
=> build(c): add missing change from #52

tachyon/math/polynomials/univariate/sparse_coefficients.h, tachyon/math/polynomials/univariate/sparse_polynomial_unittest.cc
Before this PR, `IsOne` did not check whether the degree is 0 or not. This PR fixes it.
=> fix(math): fix `IsOne` for sparse univariate polynomials

tachyon/crypto/commitments/pedersen/pedersen.h, tachyon/crypto/commitments/pedersen/pedersen_unittest.cc
This PR fix the namespace from `math` to `crypto` in `pedersen.h`.
=> chore(crypto): fix namespace from math to crypto

tachyon/math/elliptic_curves/bn/bn254/prime_field_fq.h, tachyon/math/elliptic_curves/bn/bn254/prime_field_fr.h, tachyon/math/elliptic_curves/secp/secp256k1/prime_field_fq.h, tachyon/math/elliptic_curves/secp/secp256k1/prime_field_fr.h
This is a missing change from #69.
=> fix(math): add MontgomeryTy to `PrimeFieldFq|Fr`

.github/workflows/ci.yml
Modify the script so that it runs only when there is a PR event.
There is a problem with the cpplint script when the approved PR is merged into the main branch.
=> ci: fix cpplint script to run only in PR

tachyon/math/base/BUILD.bazel, tachyon/math/base/groups.h, tachyon/math/base/groups_unittest.cc, tachyon/math/base/semigroups.h, tachyon/math/base/semigroups_unittest.cc
Previously, `Negative()` and `Inverse()` depends on `NegInPlace()` and `InverseInPlace()` internally. But there's a case that those functions require the return type to be different. In this case, the derived class needs to define its own `Negative()` and `Inverse()`.
=> feat: enable customized group inverse

tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h
- change return type for `EvaluateAllLagrangeCoefficients()` from `std::vector<F>` to `DenseCoefficients<F, MaxDegree>`
- implement `operator[]` instead of `Get()` for `UnivariateXXXCoefficients`.
=> refac(math): refactor univariate polynomial parts

tachyon/base/BUILD.bazel, tachyon/base/bits_unittest.cc, tachyon/base/random.h, tachyon/base/random_unittest.cc, tachyon/base/range.h, tachyon/base/range_unittest.cc, tachyon/device/gpu/gpu_memory_unittest.cc, tachyon/math/base/arithmetics_unittest.cc, tachyon/math/base/big_int.h, tachyon/math/elliptic_curves/msm/test/msm_test_set.h, tachyon/math/finite_fields/goldilocks_prime/prime_field_goldilocks.h, tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h
This PR implements `Range` class that covers all these intervals.
- inclusive and inclusive (a ≤ x ≤ b)
- inclusive and exlusive (a ≤ x < b)
- exclusive and inclusive (a < x ≤ b)
- exclusive and exlusive (a < x < b)
In addition, `UniformXXX()` function now makes use of this `Range`.
=> feat: implement range

tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc
Currently, the `GetRootsOfUnity()` function returns the first half of R.O.U.
In this commit, it changes to generate R.O.U based on a given size.
=> feat(math): impl function that gen entire root of unity

tachyon/math/polynomials/univariate/univariate_evaluation_domain.h
1. This adds a comment about `barycentric weight`.
2. Use precalculated `offset_pow_size_` instead of powering repeatedly.
=> perf: use precalculated offset pow size

tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_factory.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc
The `GetRootsOfDomain()` func, which was only implemented in `Radix2EvaluationDomain`, has been moved to the Base class so it can be used there as well.
And fix some bug.
=> feat(math): move radix2 funcs to parent class

tachyon/zk/plonk/BUILD.bazel, tachyon/zk/plonk/commitment.h, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/cycle_store.cc, tachyon/zk/plonk/permutation/cycle_store.h, tachyon/zk/plonk/permutation/cycle_store_unittest.cc, tachyon/zk/plonk/permutation/label.h, tachyon/zk/plonk/permutation/lookup_table.h, tachyon/zk/plonk/permutation/lookup_table_unittest.cc, tachyon/zk/plonk/permutation/permutation_argument.h, tachyon/zk/plonk/permutation/permutation_argument_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_proving_key.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc, tachyon/zk/plonk/permutation/permutation_verifying_key.h, tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc
This PR implements `keygen` logics for copy permutation. (see, [Permutation Assembly in Halo2](https://github.com/kroma-network/halo2/blob/dev/halo2_proofs/src/plonk/permutation/keygen.rs))
Once the `KZGParams` class is completed, an update will be made to add the `commit()` logic to `PermutationAssembly`.
=> feat(zk): implement halo2 permutation keygen

tachyon/math/elliptic_curves/short_weierstrass/affine_point.h, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/sw_curve.h
This PR implements point creation from x coordinate using #90.
This also adds missing `IsOnCurve` tests to `JacobianPoint`, `ProjectivePoint` and `PointXYZZ`.
=> feat(math): create point from x coordinate if (x, y) belongs to a curve point

tachyon/math/base/BUILD.bazel, tachyon/math/base/semigroups.h, tachyon/math/base/semigroups_unittest.cc, tachyon/math/elliptic_curves/affine_point_unittest.cc, tachyon/math/elliptic_curves/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/msm/kernels/cuzk/cuzk_kernels.cu.h, tachyon/math/elliptic_curves/msm/test/msm_test_set.h, tachyon/math/elliptic_curves/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/projective_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/affine_point.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/math/elliptic_curves/short_weierstrass/test/curve_config.h
- Unlike `BatchInverse`, `BatchScalarMul` doesn't have a benifit itself when doing in batch. It just parallelize if openmp feature is turned on. So to deliver its meaning clearer, this commit renames the functions.
- This PR also generalizes `ScalarMul` and `MultiScalarMul` by accepting more type as function argumetns.
=> refac: rename batch to multi

tachyon/zk/transcript/transcript.h
* add missing `public:` on `TranscriptRead` and `TranscriptWrite`
=> fix(zk): add missing `public:` on `TranscriptRead` and `TranscriptWrite`

tachyon/crypto/commitments/kzg/kzg_commitment_scheme.h, tachyon/crypto/commitments/kzg/kzg_commitment_scheme_unittest.cc, tachyon/crypto/commitments/pedersen/pedersen_commitment_scheme.h, tachyon/crypto/commitments/univariate_polynomial_commitment_scheme.h, tachyon/crypto/commitments/vector_commitment_scheme.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_factory.h, tachyon/zk/plonk/circuit/rotation.h, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/keys/verifying_key.h, tachyon/zk/plonk/keys/verifying_key_unittest.cc, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/lookup_table.h, tachyon/zk/plonk/permutation/lookup_table_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_proving_key.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc, tachyon/zk/plonk/permutation/permutation_verifying_key.h, tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc
1. The level of abstraction for `UnivariatePolynomialCommitmentScheme`(`PCS`) was elevated  to allow proofs based on various PCS. In this PR, PCSs have been modified to provide the types of `Evals`, `DensePoly` and `Domain`.
2. If a radix 2 domain is used with Modulus = 2^s * T + 1, the maximum degree of the polynomial is 2^s - 1. However, the degree of the polynomial should be chosen appropriately small as it affects performance. Therefore, in this PR, The `MaxDegree` of `Polynomial` was updated  to be used as the polynomial's degree.
(related to https://github.com/kroma-network/tachyon/pull/137 )
=> feat: enhance abstraction of pcs

tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/finite_fields/cubic_extension_field_unittest.cc, tachyon/math/finite_fields/quadratic_extension_field_unittest.cc, tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluations.h, tachyon/math/polynomials/univariate/univariate_evaluations_ops.h, tachyon/math/polynomials/univariate/univariate_evaluations_unittest.cc, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc
- To compute degree of `UnivariateEvaluations`, it needs IFFT. Does it really mean anything in evaluation form? So this commit removes `Degree()`. Instead, `UnivariatePolynomial` and `UnivariateEvaluations` have `NumElements()` to count the number of elements. e.g, Considering constant polynomial, the degree of this polynomial should be 0, but previously it returns the number of elements.
- `UnivariateEvaluations` except for zero polynomial have elements of `MaxDegree`. This affects equality operator, arithmetic operators and how it construct `UnivariateEvaluations`. e.g, `Random()` doesn't receive `degree` as an argument.
- For performance reason, zero polynomial is allowed to have an empty vector.
BREAKING CHANGE: `UnivariateEvaluations` doesn't allow arbitrary number of evaluation …
=> feat!: contain degree sized elements univariate evalutions

tachyon/crypto/hashes/sponge/poseidon/poseidon.h, tachyon/math/base/rational_field_unittest.cc, tachyon/math/base/semigroups.h, tachyon/math/elliptic_curves/msm/glv_unittest.cc, tachyon/math/finite_fields/goldilocks_prime/prime_field_goldilocks_unittest.cc, tachyon/math/finite_fields/prime_field_base.h, tachyon/math/finite_fields/prime_field_base_unittest.cc, tachyon/math/finite_fields/prime_field_unittest.cc, tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h, tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc, tachyon/zk/plonk/circuit/rotation.h, tachyon/zk/plonk/permutation/lookup_table.h, tachyon/zk/value_unittest.cc
This PR allows to call `ScalarMul` and `Pow()` with a `BigInt<1>` convertible type.
=> refac: allow call `Pow()` with `BigInt<1>` convertible

tachyon/base/parallelize.h
Sorry for the late review and now #141 is merged, I've created a PR to update the comments that should have been done in #141.
This PR fixes comments for `ParallelizeMapByChunkSize` and `ParallelizeMap`.
=> chore(base): fix comment for parallelized mapping

tachyon/crypto/commitments/kzg/kzg_commitment_scheme.h, tachyon/zk/base/halo2_prover_test.h, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc
The `PermutationAssembly::BuildVerifyingKey()` completed using the `PolynomialCommitmentScheme`::`CommitLagrange()`.
And this PR also includes a fix for the bug where the commit function fails for polynomials with leading zeros.
=> feat(zk): apply `KZGCommitmentScheme` to `PermutationAssembly`

.github/workflows/ci.yml, tachyon/c/math/elliptic_curves/generator/generator.cc, tachyon/math/base/groups.h, tachyon/math/base/rational_field_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/affine_point_correctness_gpu_test.cc, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/kernels/elliptic_curve_ops.cu.h, tachyon/math/elliptic_curves/short_weierstrass/non_affine_point_correctness_gpu_test.cc, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/projective_point_unittest.cc, tachyon/math/finite_fields/cubic_extension_field_unittest.cc, tachyon/math/finite_fields/goldilocks_prime/prime_field_goldilocks_unittest.cc, tachyon/math/finite_fields/prime_field_correctness_test.cc, tachyon/math/finite_fields/prime_field_unittest.cc, tachyon/math/finite_fields/quadratic_extension_field_unittest.cc, tachyon/node/math/elliptic_curves/short_weierstrass/affine_point.h, tachyon/node/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/node/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/node/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/node/math/finite_fields/prime_field.h, tachyon/py/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/py/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/py/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/py/math/finite_fields/prime_field.h, tachyon/zk/base/value_unittest.cc
This PR fixes CI since [this](https://github.com/kroma-network/tachyon/pull/156). The symptom is it can deduce `Negative()` signature. The reason is still unclear to me. I believe this is a bug or lack of feature in `NodeCppConstructor`. This PR doesn't solve the issue directly but rather solve in another way. It binds `operator-()` unary operator directly and removes `Negative()` method, which also might makes user confused since `Negative()` is not supported, even when `operator-()` is supported!
=> fix: fix broken binding build

tachyon/zk/base/prover_query.h, tachyon/zk/base/verifier_query.h
Unify the method names so that each `ProverQuery` and `VerifierQuery` can be used in common functions like `ConstructIntermediateSets` in a multi-point opening scheme on the prover and verifier sides.
`ConstructIntermediateSets` function is a function commonly used by Prover and Verifier.
IntermediateSets are created independently from each other with its own Query.
=> refac(zk): unify query method names

tachyon/base/strings/BUILD.bazel, tachyon/base/strings/rust_stringifier.h, tachyon/zk/base/BUILD.bazel, tachyon/zk/base/field_stringifier.h, tachyon/zk/base/point_stringifier.h, tachyon/zk/plonk/circuit/BUILD.bazel, tachyon/zk/plonk/circuit/challenge_stringifier.h, tachyon/zk/plonk/circuit/column_stringifier.h, tachyon/zk/plonk/circuit/column_type_stringifier.h, tachyon/zk/plonk/circuit/expressions/BUILD.bazel, tachyon/zk/plonk/circuit/expressions/expression_stringifier.h, tachyon/zk/plonk/circuit/phase_stringifier.h, tachyon/zk/plonk/circuit/query_stringifier.h, tachyon/zk/plonk/circuit/rotation_stringifier.h, tachyon/zk/plonk/keys/BUILD.bazel, tachyon/zk/plonk/keys/halo2/BUILD.bazel, tachyon/zk/plonk/keys/halo2/pinned_constraint_system.h, tachyon/zk/plonk/keys/halo2/pinned_evaluation_domain.h, tachyon/zk/plonk/keys/halo2/pinned_gates.h, tachyon/zk/plonk/keys/halo2/pinned_verifying_key.h, tachyon/zk/plonk/keys/halo2/pinned_verifying_key_unittest.cc, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/keys/proving_key_unittest.cc, tachyon/zk/plonk/keys/verifying_key.h, tachyon/zk/plonk/keys/verifying_key_unittest.cc, tachyon/zk/plonk/lookup/BUILD.bazel, tachyon/zk/plonk/lookup/lookup_argument_stringifier.h, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_argument_stringifier.h, tachyon/zk/plonk/permutation/permutation_verifying_key_stringifier.h
This PR implements [PinnedVerifyingKey](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk.rs#L256-L263). 
`PinnedVerifyingKey` can generate a string of `VerifyingKey` with only selective members.
And `transcript_repr` of the `VerifyingKey` is assigned a field element generated with a hash value of string of `PinnedVerifyingKey`.
=> feat(zk): fill `transcript_repr` of `VerifyingKey`

tachyon/base/BUILD.bazel, tachyon/base/random.h, tachyon/base/range.h, tachyon/base/range_unittest.cc, tachyon/zk/plonk/circuit/assembly.h
- add `begin()` and `end()` to `Range`, this leads to renaming member variables.
- add `Intersect()` and `GetSize()` to `Range`.
=> feat: add more utilities to `Range`

tachyon/zk/plonk/lookup/lookup_argument.h, tachyon/zk/plonk/lookup/lookup_committed.h, tachyon/zk/plonk/lookup/lookup_evaluated.h, tachyon/zk/plonk/lookup/lookup_permuted.h, tachyon/zk/plonk/lookup/lookup_permuted_unittest.cc
This PR contains 2 changes.
- Fix incorrect template type for `BlindedPolynomial<Poly>`
- Maintain minimum template type for classes in lookup argument.
- LookupCommitted<PCSTy> -> LookupCommitted<Poly>
- LookupEvaluatd<PCSTy> -> LookupEvaluated<Poly>
- LookupPermuted<PCSTy> -> LookupPermuted<Poly, Evals>
The rule of this is if your class is a template class, then my suggestion is your template type should be a minimum set of type of the member variables of class. So I want the class is instantiated differently depending on member variable, not the method.
=> refac(zk): use minimum template type for LookupArgument classes

tachyon/base/parallelize.h, tachyon/zk/plonk/lookup/BUILD.bazel, tachyon/zk/plonk/lookup/lookup_permuted.h, tachyon/zk/plonk/lookup/lookup_permuted_unittest.cc, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/grand_product_argument.h
While reviewing #164, I found that grand product argument can be shared between `PermutationArgument` and `LookupArgument` and this PR creates a class `GrandProductArgument` for this purpose.
See https://research.metastate.dev/on-plonk-and-plookup/ for details.
=> refac: take `GrandProductArgument::Commit()` from `LookupPermuted`

tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/zk/base/blinder.h, tachyon/zk/base/blinder_unittest.cc, tachyon/zk/plonk/circuit/table.h, tachyon/zk/plonk/circuit/table_unittest.cc, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/grand_product_argument.h, tachyon/zk/plonk/permutation/permutation_argument.h, tachyon/zk/plonk/permutation/permutation_argument_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_committed.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc, tachyon/zk/plonk/permutation/permutation_table_store.h, tachyon/zk/plonk/permutation/permutation_table_store_unittest.cc, tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc, tachyon/zk/plonk/permutation/permuted_table.h, tachyon/zk/plonk/permutation/unpermuted_table.h, tachyon/zk/plonk/permutation/unpermuted_table_unittest.cc
This PR implements `Commit()` function of `PermutationArgument` and its output structure
See [PermutationArgument::Commit](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L43-L188), and [PermutationCommitted](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L21-L28) and its [Construct](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L190-L203) method.
=> feat(zk): add committing permutations

tachyon/zk/plonk/lookup/BUILD.bazel, tachyon/zk/plonk/lookup/lookup_argument.h, tachyon/zk/plonk/lookup/lookup_committed.h, tachyon/zk/plonk/lookup/lookup_evaluated.h, tachyon/zk/plonk/lookup/lookup_permuted_unittest.cc, tachyon/zk/plonk/lookup/permute_expression_pair.h, tachyon/zk/plonk/lookup/permute_expression_pair_unittest.cc, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_argument_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_committed.h, tachyon/zk/plonk/permutation/permutation_evaluated.h
This PR implements `Open()` and `Evaluate()` functions of  classes related to permutation.
- [evaluate()](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L231-L276)
- [open()](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/permutation/prover.rs#L278-L324)
=> feat(zk): implement auxiliary classes related to permutation

tachyon/base/containers/BUILD.bazel, tachyon/base/containers/adapters.h, tachyon/base/containers/adapters_unittest.cc, tachyon/base/containers/chunked_iterator.h, tachyon/base/containers/zipped_iterator.h, tachyon/base/template_util.h
I wrote this codes in Devconnect to create `Iterator` class to help us to take rust codes in c++ easily. But i couldn't finish it completely so this is a code change that is part of that purpose. You can think of it as a preparation for that.
=> refac(base): separate iterator from adapters

tachyon/zk/plonk/lookup/BUILD.bazel, tachyon/zk/plonk/lookup/lookup_argument.h, tachyon/zk/plonk/lookup/lookup_argument_runner.h, tachyon/zk/plonk/lookup/lookup_argument_runner_impl.h, tachyon/zk/plonk/lookup/lookup_argument_runner_unittest.cc, tachyon/zk/plonk/lookup/lookup_committed.h, tachyon/zk/plonk/lookup/lookup_evaluated.h, tachyon/zk/plonk/lookup/lookup_permuted.h, tachyon/zk/plonk/permutation/grand_product_argument.h
In this PR, the lookup state transition methods were integrated into the `LookupRunner`, allowing state transitions to be monitored from a single implementation. And this will enhance the readability of the plonk's “create_proof()” function.
[FYI] `Lookup arguments proof` has intermediate 4 states in proving process.
- `LookupArgument`
- `LookupPermuted`
- `LookupCommitted`
- `LookupEvaluated`
- finally, `ProverQuery` for lookup.
=> refac(zk): integrate lookup transition methods

tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_argument.h, tachyon/zk/plonk/permutation/permutation_argument_runner.h, tachyon/zk/plonk/permutation/permutation_argument_runner_impl.h, tachyon/zk/plonk/permutation/permutation_argument_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_committed.h, tachyon/zk/plonk/permutation/permutation_evaluated.h, tachyon/zk/plonk/permutation/permutation_proving_key.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc
In this PR, the permutation state transition methods were integrated into the `PermutationArgumentRunner`, allowing state transitions to be monitored from a single implementation. And this will enhance the readability of the plonk's “create_proof()” function.
[FYI] Permutation arguments proof has intermediate 4 states in proving process.
- `PermutationArgument`
- `PermutationCommitted`
- `PermutationEvaluated`
- finally, `ProverQuery` for permutation
=> refac(zk): add permutation argument runner

tachyon/math/finite_fields/goldilocks_prime/BUILD.bazel
This fixes build bug when building goldilocks without polygon zkevm backend.
=> build(math): include prime_field.h if TACHYON_POLYGON_ZKEVM_BACKEND is not defined

tachyon/base/containers/container_util.h, tachyon/base/containers/container_util_unittest.cc, tachyon/zk/base/commitments/shplonk_extension.h, tachyon/zk/base/entities/prover.h, tachyon/zk/plonk/circuit/examples/simple_circuit.h, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/prover/BUILD.bazel, tachyon/zk/plonk/prover/argument.h, tachyon/zk/plonk/prover/argument_unittest.cc, tachyon/zk/plonk/prover/synthesizer.h, tachyon/zk/plonk/prover/synthesizer_unittest.cc, tachyon/zk/plonk/prover/witness_collection.h, tachyon/zk/plonk/prover/witness_collection_unittest.cc
This PR contains implementations of `Synthesizer` and `Argument`.
The `Synthesizer` covers the code generating advice columns in the `CreateProof()`. 
See [AdviceSingle](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/prover.rs#L135-L138), [Assigning AdviceSingles](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/prover.rs#L284-L430).
The `Argument` provides all the data required to generate a proof. In detail, it has fixed/advice/instance columns in evaluation form and coefficient form. `Argument` makes it easier to analyze data and to understand the data flow during the proof generation process. 
See [InstanceSingle](https://github.com/kroma-network/halo2/blob/7d0a369904 …
=> feat(zk): implement create proof part1

tachyon/zk/lookup/permute_expression_pair.h, tachyon/zk/plonk/circuit/BUILD.bazel, tachyon/zk/plonk/circuit/examples/BUILD.bazel, tachyon/zk/plonk/circuit/examples/simple_circuit_unittest.cc, tachyon/zk/plonk/constraint_system.h, tachyon/zk/plonk/keys/BUILD.bazel, tachyon/zk/plonk/keys/assembly.h, tachyon/zk/plonk/keys/key.h, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/keys/verifying_key.h, tachyon/zk/plonk/permutation/permutation_argument.h, tachyon/zk/plonk/prover/synthesizer_unittest.cc
This PR implements [keygen_pkxxx](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/keygen.rs#L261-L407), while achieving both reducing code duplication and enhancing memory efficiency.
For reducing code duplication, it tries to share codes between `ProvingKey` and `VerifyingKey` by moving some shared parts to a parent class `Key`.
For enhancing memory efficiency, unlike Halo2, while computing `l_first`, `l_last` and `l_active_row`, it uses a single evaluations and recycles it.
=> feat(zk): enable pkey generation

tachyon/crypto/commitments/univariate_polynomial_commitment_scheme.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/zk/base/commitments/shplonk_extension.h, tachyon/zk/base/entities/prover_unittest.cc, tachyon/zk/lookup/compress_expression.h, tachyon/zk/lookup/compress_expression_unittest.cc, tachyon/zk/lookup/lookup_argument_runner_impl.h, tachyon/zk/lookup/lookup_argument_runner_unittest.cc, tachyon/zk/plonk/circuit/examples/simple_circuit_unittest.cc, tachyon/zk/plonk/keys/assembly.h, tachyon/zk/plonk/keys/key.h, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/permutation/permutation_argument_unittest.cc, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc, tachyon/zk/plonk/permutation/permutation_table_store_unittest.cc, tachyon/zk/plonk/prover/argument_unittest.cc, tachyon/zk/plonk/prover/synthesizer.h, tachyon/zk/plonk/prover/synthesizer_unittest.cc, tachyon/zk/plonk/prover/witness_collection.h, tachyon/zk/plonk/prover/witness_collection_unittest.cc
Sometimes, we had a mistake while creating `Evals::Random()` or `Evals::UnsafeZero()` by filing it with a size not a degree. To reduce such mistakes, we shouldn't depend on it. Rather, we should create such polynomial through domain because domain knows degree required.
=> refac: create zero or random poly from domain

tachyon/crypto/commitments/kzg/kzg.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc
If we return it as a `DenseCoeffs`, we have to check whether leading coefficients are zero or not, even though we expect it to have zeros. Therefore, we change its return type to `std::vector<F>` to ensure this. FYI, Original arkworks codes use `Vec<F>` as a return type.
See
https://github.com/arkworks-rs/algebra/blob/d9527c832888ffbd9231999b30a700ce3e572c16/poly/src/domain/mod.rs#L156.
=> refac: change return type of `EvaluateAllLagrangeCoefficients`

tachyon/math/base/BUILD.bazel, tachyon/math/base/field.h, tachyon/math/base/field_unittest.cc, tachyon/math/base/rings.h, tachyon/math/elliptic_curves/short_weierstrass/affine_point_impl.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_impl.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h, tachyon/math/finite_fields/prime_field_unittest.cc, tachyon/math/finite_fields/quadratic_extension_field.h, tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc, tachyon/zk/base/entities/entity.h, tachyon/zk/lookup/lookup_pair.h, tachyon/zk/plonk/circuit/examples/circuit_test.h, tachyon/zk/plonk/circuit/examples/simple_circuit_unittest.cc, tachyon/zk/plonk/circuit/examples/simple_lookup_circuit_unittest.cc, tachyon/zk/plonk/constraint_system.h, tachyon/zk/plonk/halo2/BUILD.bazel, tachyon/zk/plonk/halo2/proof.h, tachyon/zk/plonk/halo2/proof_reader.h, tachyon/zk/plonk/halo2/prover.h, tachyon/zk/plonk/halo2/prover_test.h, tachyon/zk/plonk/halo2/verifier.h, tachyon/zk/plonk/vanishing/vanishing_argument_unittest.cc
This PR implements proof verification [verify_proof()](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/verifier.rs#L41-L240) part. This doesn't include pairing part which involves evaluating expression.
Plus, it includes some optimizaitons.
- `ConstraintSystem::ComputeDegree()` and `ConstraintSystem::ComputeBlindingFactors()` by caching.
- `UnivariateEvaluationDomain::GetElements()`.
- Parallelize `Ring::SumOfProducts()`
=> feat: implement proof verification

tachyon/crypto/commitments/kzg/BUILD.bazel, tachyon/crypto/commitments/kzg/shplonk.h, tachyon/crypto/commitments/kzg/shplonk_unittest.cc, tachyon/crypto/commitments/polynomial_openings.h, tachyon/crypto/commitments/polynomial_openings_unittest.cc, tachyon/crypto/commitments/vector_commitment_scheme.h, tachyon/zk/base/commitments/shplonk_extension.h, tachyon/zk/plonk/halo2/BUILD.bazel, tachyon/zk/plonk/halo2/prover_test.h
Implemented SHPlonk multi-opening proof verifying logic.
See https://eprint.iacr.org/2020/081.pdf
- Since the `transcripts` have been moved from zk to crypto namespace, 
it doesn't need to return the value of proofs.
It can write proofs directly into a transcript.
- Generalized `Poly` to `PolyOracle` for common use in `CreateOpeningProof()` and `VeriryOpeningProof()`.
`CreateOpeningProof()` uses the `Poly` type, and `VerifyOpeningProof()` uses the `Commitment` type for `PolyOracle`.
- Changed SHPlonk template parameters from Point type to Curve type to use Pairing.
- Replaced `absl::flat_hash_map` to `std::vector` since the order of `poly_openings` affects linear combinations.
=> feat: implement SHPlonk VerifyOpeningProof

tachyon/crypto/commitments/fri/BUILD.bazel, tachyon/crypto/commitments/fri/fri.h, tachyon/crypto/commitments/fri/fri_proof.h, tachyon/crypto/commitments/fri/fri_storage.h, tachyon/crypto/commitments/fri/fri_unittest.cc, tachyon/crypto/commitments/kzg/kzg_family.h, tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/BUILD.bazel, tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree.h, tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/binary_merkle_tree_unittest.cc, tachyon/crypto/commitments/merkle_tree/binary_merkle_tree/simple_binary_merkle_tree_storage.h, tachyon/crypto/commitments/univariate_polynomial_commitment_scheme.h, tachyon/crypto/commitments/vector_commitment_scheme.h, tachyon/crypto/transcripts/transcript.h, tachyon/math/elliptic_curves/bls12/bls12_381/BUILD.bazel, tachyon/math/elliptic_curves/bn/bn254/BUILD.bazel, tachyon/math/elliptic_curves/bn/bn384_small_two_adicity/BUILD.bazel, tachyon/math/elliptic_curves/secp/secp256k1/BUILD.bazel, tachyon/math/finite_fields/goldilocks_prime/BUILD.bazel, tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc, tachyon/zk/base/commitments/shplonk_extension.h, tachyon/zk/plonk/circuit/rotation.h
This PR implements FRI commitment. Therefore this introduces new class `FRI`, which is another child class of `UnivariatePolynomialCommitmentScheme`. In addition, this fixes a bug in `BinaryMerkleTree` and make `Goldilocks` FFT friendly field.
See here for references!
- [fri_commit_phase()](https://github.com/lambdaclass/lambdaworks/blob/703db8a535793ecc820e044b06c1b735764f0881/exercises/message/src/starks/fri/mod.rs#L20-L72),
- [fri_decommit_phase()](https://github.com/lambdaclass/lambdaworks/blob/703db8a535793ecc820e044b06c1b735764f0881/exercises/message/src/starks/fri/mod.rs#L74-L127) 
- [Anatomy of a STARK, Part 3: FRI](https://aszepieniec.github.io/stark-anatomy/fri.html)
=> feat: implement fri commitment

tachyon/math/elliptic_curves/short_weierstrass/BUILD.bazel, tachyon/math/elliptic_curves/short_weierstrass/affine_point.h, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point_unittest.cc
This PR adds `BatchNormalize()` and `BatchMapScalarFieldToPoint`, which is needed by groth16 setup that is going to be implemented.
=> feat(math): add batch functions to points

tachyon/crypto/commitments/kzg/shplonk.h, tachyon/crypto/commitments/polynomial_openings.h, tachyon/math/base/BUILD.bazel, tachyon/math/base/field.h, tachyon/math/base/ring.h, tachyon/math/base/semigroups.h, tachyon/math/polynomials/BUILD.bazel, tachyon/math/polynomials/polynomial.h, tachyon/math/polynomials/polynomial_traits.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc, tachyon/zk/plonk/halo2/verifier.h, tachyon/zk/plonk/vanishing/prover_vanishing_argument.h, tachyon/zk/plonk/vanishing/verifier_vanishing_argument.h
This replaces `Polynomial`'s `Linearize(InPlace)()` methods and manual linear combinations.
This method covers all 3 cases.
- AdditiveSemigroup's scalar multiplication e.g, affine point
- Ring's multiplication and addition e.g, polynomial
- Field's multiplication and addition e.g, prime field
=> refac: implement linear combination

tachyon/crypto/commitments/kzg/shplonk.h, tachyon/math/elliptic_curves/pairing/BUILD.bazel, tachyon/math/elliptic_curves/pairing/pairing.h, tachyon/math/elliptic_curves/pairing/pairing_unittest.cc
Previously, users should convert `G2AffinePoint` to `G2Prepared` on their own. Now what users have to do is to pass `G2AffinePoint`.
=> refac: convert `G2AffinePoint` to `G2Prepared` inside `Pairing()`

tachyon/crypto/commitments/kzg/kzg.h
This PR optimizes kzg setup by applying `BatchMapScalarFieldToPoint()`
=> perf(crypto): apply `BatchMapScalarFieldToPoint()`

tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_argument.h
This PR adds missing `TACHYON_EXPORT` macro.
=> build(zk): add `TACYON_EXPORT` to `PermutationArgument`

tachyon/math/elliptic_curves/bn/g2_prepared.h, tachyon/math/elliptic_curves/pairing/g2_projective.h
Other than this place, `NegInPlace()` is used for negation in-place operation.
=> refac(math): rename funcion name `NegateInPlace()` to `NegInPlace()`

tachyon/zk/base/entities/prover_base.h, tachyon/zk/base/entities/prover_base_unittest.cc, tachyon/zk/lookup/lookup_argument_runner_impl.h, tachyon/zk/plonk/circuit/examples/BUILD.bazel, tachyon/zk/plonk/permutation/grand_product_argument.h, tachyon/zk/plonk/prover/argument.h, tachyon/zk/plonk/prover/synthesizer.h, tachyon/zk/plonk/vanishing/prover_vanishing_argument.h
The original `Commit()` commits the input, then written to the transcript. If this method is called in parallel, it becomes impossible to guarantee the order of the internal state of the transcript and the proof array. In this commit, 3 methods were introduced as follow:
- `Commit()` returns a commitment.
- `CommitAndWriteToTranscript()` writes a commitment to transcript.
- `CommitAndWriteToProof()` writes commit a commitment to transcript and proof.
=> refac(zk): re-define commit methods of `ProverBase`

tachyon/zk/plonk/halo2/verifier.h
Since `acc` is contained in a register, addition can be done through 1 instruction. If you do `+=`, it returns a pointer, so on return inside lambda of `std::accumulate`, when assigning to `acc`, more instructions are needed such as loading address and copying values of pointer.
=> perf(zk): remove redundant assignment

Cargo.Bazel.lock, Cargo.lock, benchmark/msm/halo2/Cargo.toml, tachyon/base/buffer/buffer.h, tachyon/zk/lookup/lookup_argument.h, tachyon/zk/plonk/circuit/BUILD.bazel, tachyon/zk/plonk/circuit/gate.h, tachyon/zk/plonk/constraint_system.h, tachyon/zk/plonk/halo2/pinned_verifying_key.h, tachyon/zk/plonk/keys/proving_key.h, tachyon/zk/plonk/keys/verifying_key.h, tachyon/zk/plonk/permutation/permutation_assembly.h, tachyon/zk/plonk/permutation/permutation_assembly_unittest.cc, tachyon/zk/plonk/permutation/permutation_verifying_key.h, tachyon/zk/plonk/permutation/permutation_verifying_key_stringifier.h, tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc, vendors/halo2/BUILD.bazel, vendors/halo2/Cargo.toml, vendors/halo2/include/bn254_shplonk_proving_key.h, vendors/halo2/include/proving_key_impl_forward.h, vendors/halo2/src/bn254.rs, vendors/halo2/src/bn254_shplonk_proving_key.cc, vendors/halo2/src/buffer_reader.h, vendors/halo2/src/endian_auto_reset.h, vendors/halo2/src/lib.rs, vendors/halo2/src/proving_key.rs, vendors/halo2/src/shplonk_proving_key_impl.h
This PR creates Halo2 Proving Key by deserializing the byte array which is serialized from https://github.com/kroma-network/halo2/commit/746e4ac62ea39e8fec9f711a6b5a359dfa596818.
`permutation_proving_key_` and `vanishing_argument_` of the `ProvingKey` are going to be built internally after `Prover` binding is completed.
=> feat(zk): create halo2 proving key by deser

tachyon/crypto/commitments/kzg/BUILD.bazel, tachyon/crypto/commitments/kzg/kzg_unittest.cc, tachyon/crypto/commitments/pedersen/BUILD.bazel, tachyon/crypto/commitments/pedersen/pedersen_unittest.cc, tachyon/math/base/BUILD.bazel, tachyon/math/base/big_int_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/BUILD.bazel, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/projective_point_unittest.cc, tachyon/math/finite_fields/BUILD.bazel, tachyon/math/finite_fields/cubic_extension_field.h, tachyon/math/finite_fields/fp12_unittest.cc, tachyon/math/finite_fields/fp2_unittest.cc, tachyon/math/finite_fields/fp6_unittest.cc, tachyon/math/finite_fields/prime_field_unittest.cc, tachyon/math/finite_fields/quadratic_extension_field.h, tachyon/math/geometry/BUILD.bazel, tachyon/math/geometry/point2_unittest.cc, tachyon/math/geometry/point3_unittest.cc, tachyon/math/geometry/point4_unittest.cc, tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_evaluations_unittest.cc, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc, tachyon/zk/plonk/permutation/BUILD.bazel, tachyon/zk/plonk/permutation/permutation_proving_key_unittest.cc, tachyon/zk/plonk/permutation/permutation_verifying_key_unittest.cc
The existing tests for `Copyable`s did not cover the entire logic.
1. No test for `EstimateSize()`.
2. It did not verify that the serialized bytes are equal to the size of the object.
In this PR, I have enhanced the tests for all `Copyable`s and fixed a few bugs that were discovered.
=> fix: fix bug on copyable

tachyon/zk/plonk/circuit/examples/simple_circuit_unittest.cc, tachyon/zk/plonk/circuit/examples/simple_lookup_circuit_unittest.cc, tachyon/zk/plonk/circuit/examples/simple_lookup_v1_circuit_unittest.cc, tachyon/zk/plonk/circuit/examples/simple_v1_circuit_unittest.cc, tachyon/zk/plonk/halo2/argument.h, tachyon/zk/plonk/halo2/prover.h
In this PR, the missing reviews of [PR#238](https://github.com/kroma-network/tachyon/pull/238) are applied. (related to `Argument::GenerateInstancePolys()`)
- The bug where the wrong method was called.
- has been refactored for removing redundant code.
- The Instance type required for calling `CreateProof()` has been changed.
=> fix: fix bug on create proof

tachyon/base/json/rapidjson_util.h, tachyon/zk/lookup/BUILD.bazel, tachyon/zk/lookup/lookup_pair.h, tachyon/zk/plonk/halo2/BUILD.bazel, tachyon/zk/plonk/halo2/proof.h, tachyon/zk/plonk/halo2/proof_unittest.cc
In this PR, `RapidJsonValueConverters` for `Proof` implemented in `zk/plonk/halo2/proof.h` has been implemented.
From now on, the `Proof` can be written to a JSON file and read from the JSON file.
=> feat: implement json for proof

tachyon/zk/plonk/circuit/column_key_stringifier.h
This PR solved the issue where the rule for converting a non-zero `ColumnKey` to a string was different from rust-halo2.
The `RustDebugStringifier` does not export `Phase` of advice column while the rust-halo2 does it when the phase is non-zero. (The `ColumnType` in rust-halo2 includes `Phase`.)
[FYI] Example of stringify rules of the rust halo2:
- `ColumnType` with `Phase(0)` => "Advice",
- `ColumnType` with the other phases => "Advice { phase: Phase(1) }"
This affects the representative value of the verifying key.
=> fix(zk): match the stringify method for a non-zero `Phase` with the rust-halo2

tachyon/math/polynomials/univariate/BUILD.bazel, vendors/halo2/BUILD.bazel, vendors/halo2/include/bn254_evals.h, vendors/halo2/include/bn254_poly.h, vendors/halo2/include/bn254_rational_evals.h, vendors/halo2/include/bn254_shplonk_prover.h, vendors/halo2/src/bn254.rs, vendors/halo2/src/bn254_evals.cc, vendors/halo2/src/bn254_evals_impl.h, vendors/halo2/src/bn254_poly.cc, vendors/halo2/src/bn254_poly_impl.h, vendors/halo2/src/bn254_rational_evals.cc, vendors/halo2/src/bn254_rational_evals_impl.h, vendors/halo2/src/bn254_shplonk_prover.cc, vendors/halo2/src/circuits/simple_circuit.rs, vendors/halo2/src/circuits/simple_lookup_circuit.rs, vendors/halo2/src/prover.rs
This PR fixes to allocate memory for `Polynomial` and `Evaluations` inside c++ memory so that it can avoid copying rust memory which usually takes a lot.
=> perf: allocate poly in c++ memory when proving

tachyon/zk/plonk/layout/floor_planner/v1/v1_floor_planner.h
I found a bug while implementing fibonacci3 circuit, where `config` is being moved twice, but `Clone` wasn't called on the first case. This PR fixes such bug.
=> fix(zk): clone config before move

tachyon/crypto/commitments/polynomial_openings_unittest.cc
- Add a test polynomial with the same value as another polynomial but with a different address to test if `ShallowRefs` are correctly distinguished.
- Add logic to check the validity of each `poly_openings_vec` of `grouped_poly_openings_vec`.
=> test(crypto): reinforce `polynomial_openings_unittest`

tachyon/zk/plonk/halo2/stringifiers/BUILD.bazel, tachyon/zk/plonk/halo2/stringifiers/expression_stringifier.h, tachyon/zk/plonk/halo2/stringifiers/selector_stringifier.h
This PR fixes a bug in RustDebugStringifier. 
See https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/circuit.rs#L1099
=> fix(zk): fix `RustDebugStringifier` for `zk::Expression<F>`

tachyon/c/zk/plonk/keys/buffer_reader.h, tachyon/zk/plonk/halo2/stringifiers/point_stringifier.h
When printing a debug string and when creating a point, Halo2 treats the point at infinity specially. This PR handles both cases.
=> fix: handle point at infinity case

tachyon/math/polynomials/univariate/radix2_evaluation_domain.h
When compacting roots in place, there is a potential for collisions. Our code originally relied on the assumption that the assignments of the new compacted roots ran in order from smallest to largest index, but parallelization faults this assumption.
For example, we expect moves to occur in our roots vector in the order of indexes 0, 1, 2 like so:
0: [0] <- [0]
1: [1] <- [2]
2: [2] <- [4]
However, if the order changes to assign indexes 0, 2, 1 instead due to parallelization, we get this:
0: [0] <- [0]
1: [2] <- [4]
2: [1] <- [2] = [4]
This issue is resolved by compacting roots separately first instead of in place.
=> fix(math): correct parallel IFFT

tachyon/math/base/batch_inverse_benchmark.cc, tachyon/math/base/groups.h, tachyon/math/base/rational_field.h, tachyon/math/polynomials/univariate/lagrange_interpolation.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/zk/plonk/examples/shuffle_circuit.h, tachyon/zk/plonk/permutation/grand_product_argument.h, tachyon/zk/plonk/vanishing/circuit_polynomial_builder.h, tachyon/zk/plonk/vanishing/evaluation_input.h, tachyon/zk/plonk/vanishing/value_source.h, tachyon/zk/plonk/vanishing/vanishing_utils.h, tachyon/zk/plonk/vanishing/vanishing_utils_unittest.cc
This PR optimizes building a circuit polynomial.
The main optimization parts are as follows:
- Avoid memory allocations if possible.
- Change the value type to the reference type.
- Use `OPENMP_PARALLEL_FOR` instead of `base::Parallelize()`
- Use `BatchInverseInPlaceSerial()` within an existing parallel loop instead of `BatchInverseInPlace()`.
- Optimize algorithms
- Use `MulBy2ExpInPlace()` when computing `a * 2ᵉˣᵖ`
- Avoid calling `ToBigInt()` which incurs montgomery reduction
- Use `GetCoset()`
- Use a new feature of `GetSuccesivePowers()` in #221.
=> perf: optimize building circuit polynomial

tachyon/zk/expressions/evaluator/BUILD.bazel, tachyon/zk/expressions/evaluator/selector_replacer.h, tachyon/zk/plonk/constraint_system/BUILD.bazel, tachyon/zk/plonk/constraint_system/constraint_system.h
While it's not implemented in rust halo2 code, simple selectors are prohibited from appearing in expressions in the lookup argument by `ConstraintSystem`. So, `CHECK` is added to `LookupAny` as well, like `Lookup`.
See https://github.com/kroma-network/tachyon/blob/92f3550bc62dc5d10cfd295c0996b6620f9d46f5/tachyon/zk/expressions/evaluator/selector_replacer.h#L42-L43 and
https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/plonk/circuit.rs#L1563-L1580
=> fix(zk): add `CHECK` for `LookupAny` as well

tachyon/c/zk/plonk/halo2/prover_replay.cc, tachyon/c/zk/plonk/halo2/verifier_replay.cc, tachyon/c/zk/plonk/keys/bn254_plonk_proving_key.cc, tachyon/c/zk/plonk/keys/bn254_plonk_proving_key_impl.h, tachyon/c/zk/plonk/keys/proving_key_impl_base.h, tachyon/zk/plonk/halo2/proof_reader.h
Unlike other columns, the advice columns have their own phases. The phase iterates from 0, and the advice columns are committed when the current phase is equal to the phases of the advice columns. Therefore, commitments are created in the order of phase. However, commitments should be written to the proof in the order of column. For example, if there are commitments {C₀, C₁, C₂} corresponding to columns 0, 1, 2 and phases {0, 1, 0}, previously, the proof was read in the order of C₀, C₂, C₁, even though the correct order should have been C₀, C₁, C₂. In this commit, the order to read the columns has been corrected.
=> fix(zk): read commitments from proof in the correct order

tachyon/math/base/semigroups.h
This PR removes redundant inner for loops inside `OPENMP_PARALLEL_FOR` loop in `MultiScalarMul`.
=> perf(math): remove redundant for loop

tachyon/zk/plonk/constraint_system/constraint_system.h, tachyon/zk/plonk/constraint_system/constraint_system_unittest.cc
I've referred to lookups in simple_lookup_circuit.h and [dev.rs](https://github.com/kroma-network/halo2/blob/7d0a36990452c8e7ebd600de258420781a9b7917/halo2_proofs/src/dev.rs#L1595-L1895).
This PR should be merged after #286.
=> test(zk): add unit tests for `ConstraintSystem`

tachyon/crypto/commitments/kzg/kzg.h, tachyon/math/elliptic_curves/short_weierstrass/BUILD.bazel, tachyon/math/elliptic_curves/short_weierstrass/affine_point.h, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h
This PR optimizes `KZG::UnsafeSetup` by parallelizing `AffinePoint::DoBatchMapScalarFieldToPoint`.
Note that there is a side effect; `BatchMapScalarFieldToPointSerial` method is removed since `BatchNormalizeSerial` is called inside `base::Parallelize`.
Tachyon's `UnsafeSetup` is now 40% faster than halo2's.
=> perf: optimize `KZG::UnsafeSetup`

tachyon/zk/lookup/halo2/prover_impl.h
In this PR, code changes that made code run in parallel when they should not do so were reverted.
=> fix(zk): fix bug on the PR #302

tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc, tachyon/zk/plonk/vanishing/circuit_polynomial_builder.h, tachyon/zk/plonk/vanishing/vanishing_utils.h, tachyon/zk/plonk/vanishing/vanishing_utils_unittest.cc
In this PR, FFT and IFFT was improved by removing redundant calculations.
1. `InOutHelper` and `OutInHelper` were modified so that `GetRootsOfUnity` is no longer called upon their invocation. Instead, the domain is precomputed and stored at the time of creation.
2. `CoeffToExtendedPart` redundantly created the coset domain every time it was called. To fix this, the coset domain is now created only once by its caller.
=> perf: optimize FFT and IFFT

tachyon/math/base/groups.h, tachyon/math/base/semigroups.h, tachyon/math/elliptic_curves/bn/bn254/prime_field_fq.h, tachyon/math/elliptic_curves/bn/bn254/prime_field_fr.h, tachyon/math/elliptic_curves/secp/secp256k1/prime_field_fq.h, tachyon/math/elliptic_curves/secp/secp256k1/prime_field_fr.h, tachyon/math/finite_fields/prime_field.h, tachyon/math/finite_fields/prime_field_gpu.h, tachyon/math/finite_fields/prime_field_gpu_debug.h
This PR optimizes `IsOne()` by avoiding montgomery reduction and optimizes some functions by not multiplying the operand if it is one.
=> perf(math): optimize usage of is one

tachyon/c/math/elliptic_curves/msm/msm_gpu.h, tachyon/c/math/elliptic_curves/msm/msm_input_provider.h, tachyon/c/zk/plonk/halo2/prover_impl_base.h, tachyon/c/zk/plonk/halo2/prover_replay.cc, tachyon/c/zk/plonk/halo2/verifier_replay.cc, tachyon/crypto/hashes/prime_field_serializable.h, tachyon/crypto/hashes/sponge/poseidon/poseidon_config.h, tachyon/device/gpu/gpu_memory_unittest.cc, tachyon/math/base/groups.h, tachyon/math/base/semigroups_unittest.cc, tachyon/math/elliptic_curves/bn/generator/generator.cc, tachyon/math/elliptic_curves/msm/algorithms/pippenger/pippenger.h, tachyon/math/elliptic_curves/short_weierstrass/generator/generator.cc, tachyon/math/finite_fields/generator/ext_prime_field_generator/ext_prime_field_generator.cc, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h, tachyon/zk/expressions/evaluator/simple_evaluator_unittest.cc, tachyon/zk/lookup/halo2/test/compress_expression_test.h, tachyon/zk/plonk/base/ref_table_unittest.cc, tachyon/zk/plonk/halo2/argument_data.h, tachyon/zk/plonk/halo2/proof.h, tachyon/zk/plonk/halo2/verifier.h, tachyon/zk/plonk/permutation/grand_product_argument.h, tachyon/zk/plonk/permutation/permutation_table_store_unittest.cc
Since `absl::Span<T>` can be constructed if the type `EnableIfConvertibleFrom<T>`  is true, we can convert the container to `absl::Span<T>` without explicit conversion! Therefore, this PR removes these redundant calls.
```c++
// Explicit reference constructor for a mutable `Span<T>` type. Can be
// replaced with MakeSpan() to infer the type parameter.
template <typename V, typename = EnableIfConvertibleFrom<V>,
typename = EnableIfValueIsMutable<V>,
typename = span_internal::EnableIfNotIsView<V>>
explicit Span(
V& v
ABSL_ATTRIBUTE_LIFETIME_BOUND) noexcept  // NOLINT(runtime/references)
: Span(span_internal::GetData(v), v.size()) {}
// Implicit reference constructor for a read-only `Span<const T>` type
template <typename V, typename = EnableIfConvertibleFrom<V>,
typename = …
```
=> refac: remove redundant calls to `absl::MakeSpan()` and `absl::MakeConstSpan()`

docs/development/conventions.md
Using a relative link as I think it's cleaner, esp in case there's a change to org/repo name.
=> fix: use relative link

tachyon/zk/r1cs/groth16/verifying_key.h
The number should have been `l_g1_query_jacobian.size()`, which represents the number of affine points to be normalized. However, occasionally it was set to 2, this PR fixes the bug.
=> fix(zk): fix number of affine points to be normalized

vendors/halo2/src/circuits/shuffle_circuit.rs, vendors/halo2/src/circuits/simple_circuit.rs, vendors/halo2/src/circuits/simple_lookup_circuit.rs
This PR drops `pk_bytes` immediately after deserialization.
=> perf(halo2): drop `pk_bytes` immediately after deserialization

Cargo.Bazel.lock, Cargo.lock
In 88e4660, cargo lock files were updated wrong, causing ci failure with the error message below. This PR fixes it.
```
ERROR: /private/var/tmp/_bazel_takim9999/3a7efe9626017559f78ec48c055ca385/external/crate_index__ahash-0.8.8/BUILD.bazel:22:13: Compiling Rust rlib ahash v0.8.8 (14 files) failed: (Exit 1): process_wrapper failed: error executing command (from target @crate_index__ahash-0.8.8//:ahash) bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper --env-file bazel-out/darwin_arm64-dbg/bin/external/crate_index__ahash-0.8.8/ahash_build_script.env ... (remaining 33 arguments skipped) error[E0658]: use of unstable library feature 'stdsimd'
--> external/crate_index__ahash-0.8.8/src/operations.rs:124:24
|
124 |     let res = unsafe { …
```
=> build: fix cargo lock files

tachyon/base/BUILD.bazel, tachyon/base/openmp_util.h, tachyon/base/random.h, tachyon/crypto/sumcheck/multilinear/BUILD.bazel, tachyon/crypto/sumcheck/multilinear/multilinear_sumcheck.h, tachyon/crypto/sumcheck/multilinear/multilinear_sumcheck_unittest.cc, tachyon/crypto/sumcheck/multilinear/sumcheck_prover.h, tachyon/crypto/sumcheck/multilinear/sumcheck_prover_msg.h, tachyon/crypto/sumcheck/multilinear/sumcheck_prover_msg_unittest.cc, tachyon/crypto/sumcheck/multilinear/sumcheck_proving_key.h, tachyon/crypto/sumcheck/multilinear/sumcheck_proving_key_unittest.cc, tachyon/crypto/sumcheck/multilinear/sumcheck_verifier.h, tachyon/crypto/sumcheck/multilinear/sumcheck_verifier_msg.h, tachyon/crypto/sumcheck/multilinear/sumcheck_verifier_msg_unittest.cc, tachyon/crypto/sumcheck/multilinear/sumcheck_verifying_key.h, tachyon/crypto/sumcheck/multilinear/sumcheck_verifying_key_unittest.cc, tachyon/crypto/sumcheck/sumcheck_proving_key_unittest.cc, tachyon/crypto/sumcheck/sumcheck_verifying_key.h, tachyon/math/polynomials/multivariate/BUILD.bazel, tachyon/math/polynomials/multivariate/linear_combination.h, tachyon/math/polynomials/multivariate/linear_combination_term.h, tachyon/math/polynomials/multivariate/linear_combination_unittest.cc, tachyon/math/polynomials/multivariate/multilinear_dense_evaluations.h, tachyon/math/polynomials/multivariate/multivariate_sparse_coefficients.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h
Implements and tests an interactive multilinear sumcheck protocol involving a prover and a verifier.
Uses [arkwork's sumcheck](https://github.com/arkworks-rs/sumcheck/tree/master/src/ml_sumcheck) as a coding reference and uses [this file](https://people.cs.georgetown.edu/jthaler/sumcheck.pdf) as a reference for the sumcheck  protocol.
=> feat: implement multilinear sumcheck

tachyon/math/finite_fields/generator/prime_field_generator/build_defs.bzl, third_party/ffiasm/workspace.bzl, vendors/circom/build_defs.bzl, vendors/circom/circomlib/CPPLINT.cfg, vendors/circom/circomlib/generated/.clang-format, vendors/circom/circomlib/generated/README.md, vendors/circom/circomlib/generated/bls12381/BUILD.bazel, vendors/circom/circomlib/generated/bn128/BUILD.bazel, vendors/circom/circomlib/generated/build_defs.bzl, vendors/circom/circomlib/generated/common/BUILD.bazel, vendors/circom/circomlib/generated/common/calcwit.cpp, vendors/circom/circomlib/generated/common/calcwit.cpp.diff, vendors/circom/circomlib/generated/common/calcwit.hpp, vendors/circom/circomlib/generated/common/calcwit.hpp.diff, vendors/circom/circomlib/generated/common/circom.hpp, vendors/circom/circomlib/generated/common/circom.hpp.diff, vendors/circom/circomlib/generated/goldilocks/BUILD.bazel, vendors/circom/circomlib/generated/grumpkin/BUILD.bazel, vendors/circom/circomlib/generated/pallas/BUILD.bazel, vendors/circom/circomlib/generated/secq256r1/BUILD.bazel, vendors/circom/circomlib/generated/vesta/BUILD.bazel, vendors/circom/circomlib/r1cs/BUILD.bazel, vendors/circom/circomlib/r1cs/r1cs_parser_unittest.cc, vendors/circom/examples/BUILD.bazel, vendors/circom/examples/compute_witness_multiplier_3.cc, vendors/circom/examples/multiplier_3.circom, vendors/circom/examples/multiplier_n.circom
This PR enables generating circom witness.
Please test this by running this command!
```shell
cd vendors/circom
bazel run //examples:compute_witness_multiplier_3
```
You can find `multiplier_3.wtns` in `bazel-bin/examples/compute_witness_multiplier_3.runfiles/kroma_network_circom`.
See also https://docs.circom.io/getting-started/computing-the-witness/.
=> feat: support generating circom witness

vendors/halo2/include/bn254_gwc_prover.h, vendors/halo2/include/bn254_shplonk_prover.h, vendors/halo2/src/bn254.rs, vendors/halo2/src/bn254_gwc_prover.cc, vendors/halo2/src/bn254_shplonk_prover.cc, vendors/halo2/src/prover.rs
This PR eliminates the need to copy a structure with potentially large memory when returning `s_g2()`.
=> perf(halo2): avoid copying when returning `s_g2()`

vendors/halo2/src/circuits/shuffle_circuit.rs, vendors/halo2/src/circuits/simple_circuit.rs, vendors/halo2/src/circuits/simple_lookup_circuit.rs
To reduce memory usage in Halo2, this PR drops `pk` immediately after its usage.
=> perf(halo2): drop `pk` immediately right after it is used

tachyon/c/BUILD.bazel, tachyon/cc/BUILD.bazel
This PR addresses the issue where `//tachyon/c:tachyon_hdrs` was missing `tachyon/c/version_generated.h`, and `//tachyon/cc:tachyon_hdrs` was missing `tachyon/cc/version.h` and `tachyon/cc/version_generated.h`. These changes ensure that the headers are properly included.
=> build: add missing header to tachyon hdrs

tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field_x86_special.cc
This PR avoid copying in prime field operations.
=> perf(math): avoid copying in prime field operations

Dockerfile.halo2.jammy
This PR adds missing bazel build config for linux.
=> build: fix bazel build configurations for halo2 to be on linux

tachyon/crypto/commitments/kzg/shplonk.h, tachyon/crypto/commitments/polynomial_openings.h
The need for this optimization stems from the internal copying that occurs during multiplication and division between the polynomials. With `Poly& * operand`, copying occurs twice, so we use `Poly * operand` instead so that copying occurs just once.
```c++
Poly Func() {
Poly& poly;
Poly operand;
return poly *= operand; // copying twice
}
```
```c++
Poly Func() {
Poly& poly;
Poly operand;
return poly * operand; // copying once
}
```
=> perf(crypto): avoid copying twice when returning a polynomial

tachyon/device/tracking_allocator.cc, tachyon/math/elliptic_curves/bn/bn_curve.h, tachyon/math/elliptic_curves/msm/algorithms/cuzk/cuzk.h, tachyon/math/elliptic_curves/msm/kernels/bellman/bellman_msm_kernels.cu.h, tachyon/math/elliptic_curves/short_weierstrass/affine_point_impl.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_impl.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h, tachyon/math/finite_fields/fp12.h, tachyon/math/finite_fields/fp6.h, tachyon/math/finite_fields/prime_field_util.cc, tachyon/math/finite_fields/quadratic_extension_field.h, tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/zk/plonk/constraint_system/constraint_system.h, tachyon/zk/r1cs/constraint_system/quadratic_arithmetic_program.h, tachyon/zk/r1cs/groth16/prove.h
This commit enhances performance by utilizing the `c = a op b` style instead of `c = a; c inplace-op b`. While the former style is nearly as performant as the latter when `a` is movable, it becomes inefficient when operating on prime fields or points on elliptic curves that are not able to be moved. This change ensures better performance and readability, reducing 2 lines to 1. Note that irrelevant changes may occur due to this adjustment.
=> perf: avoid in place operator where ineffective

tachyon/zk/expressions/evaluator/selector_replacer_unittest.cc
`ReplaceSelectors()` only crashes only when compiled with debug mode, so this commit enables it using `EXPECT_DEBUG_DEATH`.
```c++
template <typename F>
class SelectorsReplacer : public Evaluator<F, std::unique_ptr<Expression<F>>> {
std::unique_ptr<Expression<F>> Evaluate(const Expression<F>* input) override {
if (selector.is_simple()) {
LOG(DFATAL) << "Simple selector found in lookup argument";
}
}
```
=> test(zk): enable `SelectorReplacerTest.Selector` test on optimization mode

third_party/goldilocks/goldilocks.BUILD
This is to resolve a runtime error of Goldilocks when building with g++-12 and optimization mode.
Plus, if we want to build with avx512, we need to add `defines = ["__AVX512__"]`, too.
See
https://github.com/0xPolygonHermez/zkevm-prover/blob/93c36f120c3201bfaf12b8f6f2796f53e72193ff/Makefile#L31-L37 for more details.
=> fix: change compile option `maxvx512f` to `mavx2` for goldilocks

benchmark/ec/simple_ec_benchmark_reporter.h, benchmark/fft/simple_fft_benchmark_reporter.h, benchmark/msm/simple_msm_benchmark_reporter.h, tachyon/base/console/table_writer.h, tachyon/device/gpu/gpu_util.h
Fixes compile errors with gcc/++-13 when running `bazel build --config linux`.
Refer to [Header dependency changes](https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes) for more information.
=> fix: fix gcc-13 compile errors

tachyon/math/finite_fields/generator/prime_field_generator/config.h.tpl, tachyon/math/finite_fields/generator/prime_field_generator/prime_field_generator.cc, tachyon/math/finite_fields/mersenne31/BUILD.bazel
Since mersenne 31 has only 1 2-adicity, it should be treated as non-fft friendly.
```
M = 2³¹ - 1
M - 1 = 2³¹ - 2 = 2(2³⁰ - 1)
```
=> build(math): generate m31 field as non fft friendly field

docs/how_to_use/how_to_build.md
This PR changes .bazelrc.user lines about path-related environment variables to only be used when building with cuda config.
=> docs: update how to build

tachyon/zk/plonk/base/multi_phase_owned_table.h, tachyon/zk/plonk/base/owned_table.h, tachyon/zk/plonk/vanishing/circuit_polynomial_builder.h, tachyon/zk/plonk/vanishing/evaluation_input.h, tachyon/zk/plonk/vanishing/vanishing_argument.h
This PR refactors(mostly) and optimizes `CircuitPolynomialBulider`
=> refac(zk): refactor circuit polynomial builder

benchmark/fft/fft_benchmark.cc, benchmark/fft/fft_runner.h, tachyon/c/math/polynomials/univariate/bn254_univariate_evaluation_domain.cc, tachyon/c/math/polynomials/univariate/bn254_univariate_evaluation_domain.h
This commit ensures that both arkworks and Tachyon perform FFT benchmarks without incurring any copy overhead. Previously, arkworks (I)FFT didn't incur any copy overhead, while Tachyon did. Now, both implementations are configured to avoid copy overhead for consistency and accurate benchmarking.
=> test: run (I)FFT benchmark under uniform conditions

tachyon/math/base/big_int.h, tachyon/math/base/rational_field.h, tachyon/math/base/semigroups.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_impl.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point_impl.h, tachyon/math/finite_fields/cubic_extension_field.h, tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field_x86_special.cc, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field_x86_special.h, tachyon/math/finite_fields/prime_field_generic.h, tachyon/math/finite_fields/prime_field_gpu.h, tachyon/math/finite_fields/prime_field_gpu_debug.h, tachyon/math/finite_fields/quadratic_extension_field.h, tachyon/math/polynomials/multivariate/multilinear_extension_ops.h, tachyon/math/polynomials/multivariate/multivariate_polynomial_ops.h, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_evaluations.h, tachyon/math/polynomials/univariate/univariate_evaluations_ops.h, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_polynomial_ops.h, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc, tachyon/zk/base/value.h
This PR avoids copying on semigroup operations, which are `Add()`, `Mul()`, `Double()` and `Square()`.
=> perf: avoid copying on semigroup operations

tachyon/math/base/big_int.cc, tachyon/math/finite_fields/generator/prime_field_generator/prime_field_x86.h.tpl, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field_x86_special.cc, tachyon/math/finite_fields/prime_field_generic.h, tachyon/math/finite_fields/prime_field_gpu.h, tachyon/math/finite_fields/prime_field_gpu_debug.h
This PR adds the following features:
1. helpful error message when failing to parse `BigInt<N>`.
2. add range check to `PrimeFieldXXX::From(Dec|Hex)String`.
=> feat(math): add range check to string conversion methods

tachyon/math/base/big_int_unittest.cc, tachyon/math/finite_fields/BUILD.bazel, tachyon/math/finite_fields/prime_field_generator_unittest.cc, tachyon/math/finite_fields/prime_field_gpu.h, tachyon/math/finite_fields/prime_field_gpu_debug.h, tachyon/math/finite_fields/prime_field_gpu_unittest.cc, tachyon/math/finite_fields/prime_field_unittest.cc
This PR addresses the compilation error that occurred in #388.
=> fix(math): add missing changes from #388

tachyon/math/finite_fields/BUILD.bazel, tachyon/math/finite_fields/generator/prime_field_generator/build_defs.bzl, tachyon/math/finite_fields/generator/prime_field_generator/cpu.h.tpl, tachyon/math/finite_fields/prime_field_fallback.h, tachyon/math/finite_fields/small_prime_field.h, tachyon/math/finite_fields/small_prime_field_generic.h
This refactor renames the following files:
- `prime_field_generic.h` to `prime_field_fallback.h`: This file is enabled when there's no optimized assembly code for the building architecture, hence the name fallback.
- `small_prime_field_generic.h` to `small_prime_field.h`: This file is enabled for all prime fields whose modulus is less than 32 bits, hence the simplified name.
=> refac(math): rename filenames

tachyon/base/containers/circular_deque.h, tachyon/base/numerics/README.md, tachyon/base/ranges/algorithm.h, tachyon/base/scoped_generic.h
Fixes spelling typos in comments and docs
=> chore: fix typos

tachyon/math/circle/stark/BUILD.bazel, tachyon/math/finite_fields/generator/prime_field_generator/build_defs.bzl, tachyon/math/finite_fields/generator/prime_field_generator/config.h.tpl, tachyon/math/finite_fields/generator/prime_field_generator/prime_field_generator.cc, tachyon/math/finite_fields/mersenne31/BUILD.bazel, tachyon/math/finite_fields/prime_field_generator_unittest.cc, tachyon/math/finite_fields/small_prime_field.h, tachyon/math/finite_fields/test/BUILD.bazel, tachyon/math/polynomials/multivariate/multilinear_dense_evaluations_unittest.cc
This PR implements followings
1. Adds faster reductions for `addition`, `subtraction` and `negation`  when the modulus of the prime field is less than 2³¹ + 1.
2. Removes redundant `Reduce()` function calls
3. Enables 32-bit custom reductions for small prime fields.
=> perf(math): add fast reduction for a special case

BUILD.bazel, bazel/tachyon.bzl, bazel/tachyon_cc.bzl, docs/how_to_use/how_to_build.md, tachyon/math/finite_fields/generator/prime_field_generator/build_defs.bzl, tachyon/math/finite_fields/goldilocks/BUILD.bazel, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field.h, tachyon/math/finite_fields/goldilocks/goldilocks_prime_field_x86_special.cc
@zkbitcoin reported in Tachyon Discussion group that he has a trouble with using tachyon with ffiasm on. In order to resolve the issue, this commit adds a build option without ffiasm.
=> build: add build option to disable assembly optimized field

tachyon/zk/plonk/halo2/README.md
Benchmarking results are updated with Tachyon @ commit https://github.com/kroma-network/tachyon/commit/9eb36174b50022f58ba7fd7b50ef1902bf008d2b
merge after #408
=> docs: update tachyon vs halo2 benchmarking results

tachyon/math/base/BUILD.bazel, tachyon/math/base/field.h, tachyon/math/base/groups.h, tachyon/math/base/groups_unittest.cc, tachyon/math/matrix/BUILD.bazel, tachyon/math/matrix/matrix_types.h, tachyon/math/matrix/matrix_types_unittest.cc, tachyon/math/matrix/prime_field_num_traits.h
This PR prepares for [Poseidon2](https://eprint.iacr.org/2023/323) Hash function. In Poseidon2, the **Matirx for the Internal Round** is a diagonal matrix. So this PR mainly adds `DiagonalMatrix`. Additionally, it adds minor improvements on `Matrix` types.
=> feat(math): prepare poseidon2

docs/how_to_use/how_to_build.md, tachyon/base/openmp_util.h, tachyon/base/threading/platform_thread_linux.cc, tachyon/math/base/groups.h, tachyon/math/base/semigroups.h, tachyon/math/elliptic_curves/msm/fixed_base_msm.h, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz.h, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_impl.h, tachyon/math/elliptic_curves/short_weierstrass/projective_point.h, tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, vendors/halo2/BUILD.bazel
This PR enables building tachyon with clang on ubuntu 22.04
=> build: support building with clang on ubuntu

tachyon/zk/r1cs/groth16/proof.h, vendors/circom/README.md, vendors/circom/prover_main.cc
This PR adds a `no_zk` and `verify` flag for circom benchmarking.
With the `no_zk` flag, you can create proof without zk. By default zk is enabled. You can use this flag in case you want to compare the proof with rapidsnark.
For benchmarking proving speed, we do not need to verify proof everytime. So, `verify` flag is added in case you want to verify the proof with public inputs.
=> test: add `no_zk` and `verify` flag for circom benchmarking

tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/lagrange_interpolation.h, tachyon/math/polynomials/univariate/univariate_dense_coefficients.h, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_polynomial.h, tachyon/math/polynomials/univariate/univariate_polynomial_ops.h, tachyon/math/polynomials/univariate/univariate_sparse_coefficients.h, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc, tachyon/zk/plonk/vanishing/vanishing_prover_impl.h
- Change `RemoveHighDegreeZeros()` to `RemoveZeros()` in univariate spare polynomial
- Enforce clean construction of polynomials. After this change, all poly operations are expected to operate on _clean_ polynomials and output _clean_ polynomials.
=> feat(math): impl remove zeros for sparse univariate poly

tachyon/crypto/commitments/test/bn254_kzg_polynomial_openings.json, tachyon/math/elliptic_curves/short_weierstrass/affine_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/jacobian_point_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/point_xyzz_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/projective_point_unittest.cc, tachyon/math/finite_fields/cubic_extension_field_unittest.cc, tachyon/math/finite_fields/prime_field_base.h, tachyon/math/finite_fields/prime_field_base_unittest.cc, tachyon/math/finite_fields/quadratic_extension_field_unittest.cc, tachyon/math/geometry/point2_unittest.cc, tachyon/math/geometry/point3_unittest.cc, tachyon/math/geometry/point4_unittest.cc, tachyon/math/polynomials/univariate/univariate_dense_polynomial_unittest.cc, tachyon/math/polynomials/univariate/univariate_evaluations_unittest.cc, tachyon/math/polynomials/univariate/univariate_sparse_polynomial_unittest.cc
This PR improves prime field (de)serializations in several aspects.
=> feat!(math): improve prime field (de)serialization

vendors/circom/README.md, vendors/circom/prover_main.cc
Add benchmarking functionality to prover_main.cc:
-Introduce '-n' flag for specifying number of proof generation runs
-Implement loop for multiple proof generations
-Calculate and display average and maximum execution times
-Add per-run timing measurements
-These changes enable performance analysis across multiple iterations.
=> feat(circom): introduce `-n` flag for specifying number of proof generation

tachyon/math/finite_fields/BUILD.bazel, tachyon/math/finite_fields/baby_bear/BUILD.bazel, tachyon/math/finite_fields/baby_bear/packed_baby_bear.h, tachyon/math/finite_fields/koala_bear/BUILD.bazel, tachyon/math/finite_fields/koala_bear/packed_koala_bear.h, tachyon/math/finite_fields/mersenne31/packed_mersenne31.h, tachyon/math/finite_fields/packed_prime_field_traits_forward.h, tachyon/math/finite_fields/prime_field_base.h, tachyon/math/matrix/BUILD.bazel, tachyon/math/matrix/matrix_utils.h, tachyon/math/matrix/matrix_utils_unittest.cc, tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/math/polynomials/univariate/mixed_radix_evaluation_domain.h, tachyon/math/polynomials/univariate/naive_batch_fft.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain_unittest.cc, tachyon/math/polynomials/univariate/two_adic_subgroup.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/zk/plonk/constraint_system/constraint_system.h, tachyon/zk/plonk/layout/assignment.h, tachyon/zk/plonk/vanishing/vanishing_utils.h
In preparation for sp1, this PR implements [`Radix2DitParallel`](https://github.com/Plonky3/Plonky3/blob/33b94a8ebaf8fbaace3def6e792cba0dd97b3c42/dft/src/radix_2_dit_parallel.rs) and its related testing.
=> feat: impl `Radix2DitParallel`

tachyon/math/finite_fields/generator/prime_field_generator/small_prime_field_config.h.tpl, tachyon/zk/air/plonky3/base/BUILD.bazel, tachyon/zk/air/plonky3/base/multi_field32_conversions.h, tachyon/zk/air/plonky3/challenger/BUILD.bazel, tachyon/zk/air/plonky3/challenger/challenger.h, tachyon/zk/air/plonky3/challenger/challenger_traits_forward.h, tachyon/zk/air/plonky3/challenger/duplex_challenger.h, tachyon/zk/air/plonky3/challenger/duplex_challenger_unittest.cc, tachyon/zk/air/plonky3/challenger/hash_challenger.h, tachyon/zk/air/plonky3/challenger/hash_challenger_unittest.cc, tachyon/zk/air/plonky3/challenger/multi_field32_challenger.h, tachyon/zk/air/plonky3/challenger/multi_field32_challenger_unittest.cc
This PR implements all the challengers except for `SerializingChallenger` listed [here](https://github.com/Plonky3/Plonky3/tree/7bb6db50594e159010f11c97d110aa3ee121069b/challenger/src). The reason `SerializingChallenger` is not implemented is that it uses byte hashes such as keccak256 or blake3, which are wrapped with a Hasher that we haven't implemented yet.
=> feat(zk): implement plonky3 challenges

vendors/halo2/README.md
This is a missing change from #458.
=> docs(halo2): update Halo2 migration guide

docs/how_to_use/how_to_build.md, vendors/circom/.bazelrc, vendors/circom/WORKSPACE
Since https://github.com/kroma-network/tachyon/pull/426 has been merged, this PR prepares the Circom prover to produce a proof with ICICLE.
=> build: prepare circom proof generation with cuda

tachyon/c/zk/plonk/halo2/bn254_prover.cc, tachyon/c/zk/plonk/halo2/bn254_prover.h, tachyon/c/zk/plonk/halo2/bn254_prover_unittest.cc, vendors/halo2/include/bn254_prover.h, vendors/halo2/src/bn254.rs, vendors/halo2/src/bn254_prover.cc, vendors/halo2/src/prover.rs
Previously, `create_proof()` committed to polynomials or evaluations and then performed batch normalization. This approach was inefficient on the CPU (though acceptable on the GPU, as `ProjectivePoint` was returned) because `commit()` returned `PointXYZZ`, which then needed conversion to `ProjectivePoint` and finally to `AffinePoint`. This process has now been optimized by directly converting `PointXYZZ` to `AffinePoint`, thus improving performance.
=> perf(halo2): apply batch commitment in `create_proof()`

README.md, tachyon/crypto/commitments/pedersen/BUILD.bazel, tachyon/crypto/commitments/pedersen/pedersen.h, tachyon/crypto/commitments/pedersen/pedersen_unittest.cc
This PR enables pedersen commitment using GPU.
=> feat: enable pedersen gpu

benchmark/ec/ec_double_benchmark_gpu.cc, tachyon/base/containers/BUILD.bazel, tachyon/base/containers/container_util.h, tachyon/math/base/batch_inverse_benchmark.cc, tachyon/math/elliptic_curves/msm/test/fixed_base_msm_test_set.h, tachyon/math/elliptic_curves/msm/test/variable_base_msm_test_set.h, tachyon/math/elliptic_curves/test/BUILD.bazel, tachyon/math/elliptic_curves/test/random.h, tachyon/zk/base/nested_for_loop_openmp_benchmark.cc, tachyon/zk/base/parallelize_benchmark.cc, vendors/circom/benchmark/circom_benchmark.cc
In benchmarks, data is typically created using base::CreateVector(). However, since benchmarks generate a large amount of data, running this process in parallel is beneficial. This PR implements parallel data creation for benchmarks.
=> test: optimize benchmark test

tachyon/zk/plonk/examples/circuit_test.h, tachyon/zk/plonk/examples/circuit_test_data.h, tachyon/zk/plonk/examples/fibonacci/fibonacci1_circuit_test_data.h, tachyon/zk/plonk/examples/fibonacci/fibonacci2_circuit_test_data.h, tachyon/zk/plonk/examples/fibonacci/fibonacci3_circuit_test_data.h, tachyon/zk/plonk/examples/multi_lookup_circuit_test_data.h, tachyon/zk/plonk/examples/shuffle_circuit_test_data.h, tachyon/zk/plonk/examples/simple_circuit_test_data.h, tachyon/zk/plonk/examples/simple_lookup_circuit_test_data.h, tachyon/zk/plonk/examples/tracking_testing.md
This PR fixes typos, changes variable names, and updates the `tracking_testing.md` doc for example circuit testing.
=> docs: fix circuit testing doc

tachyon/math/base/arithmetics.h
This PR addresses the issue faced by many in the Tachyon discussion group when building with **g++-10**. For your information, **g++-11** is the default compiler in **Ubuntu 22.04**, and **g++-9** is the default compiler in **Ubuntu 20.04**. We guide users to upgrade to **g++-10** [to build on Ubuntu 20.04](https://github.com/kroma-network/tachyon/blob/main/docs/how_to_use/how_to_build.md#build-on-ubuntu-2004).
I checked build is possible using this Dockerfile
```dockerfile
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
apt-get install -y curl gnupg git g++-10 libgmp-dev libomp-dev python3 python3-pip zip
RUN pip install numpy
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg && \
mv bazel.gpg /etc/apt/trusted.gpg.d/ && \ …
```
=> build(math): include a different header if gcc version ≤ 10

tachyon/base/compiler_specific.h, tachyon/base/files/BUILD.bazel, tachyon/base/files/bin_file.cc, tachyon/base/files/bin_file.h, tachyon/base/files/memory_mapped_file.cc, tachyon/base/files/memory_mapped_file.h, tachyon/base/files/memory_mapped_file_posix.cc, tachyon/base/system/BUILD.bazel, tachyon/base/system/sys_info.h, tachyon/base/system/sys_info_posix.cc, vendors/circom/benchmark/circom_benchmark.cc, vendors/circom/benchmark/rapidsnark_runner.h, vendors/circom/benchmark/runner.h, vendors/circom/benchmark/tachyon_runner.h, vendors/circom/circomlib/circuit/adder_circuit_unittest.cc, vendors/circom/circomlib/circuit/multiplier_3_circuit_unittest.cc, vendors/circom/circomlib/wtns/BUILD.bazel, vendors/circom/circomlib/wtns/wtns.h, vendors/circom/circomlib/zkey/BUILD.bazel, vendors/circom/circomlib/zkey/zkey.h, vendors/circom/prover_main.cc
Zkey and wtns files are now read using `mmap()` and is much faster!
Before
```
Start parsing zkey
Time taken for parsing zkey: 5.97333 s
Start parsing witness
Time taken for parsing witness: 0.319247 s
```
After
```
Start parsing zkey
Time taken for parsing zkey: 0.611177 s
Start parsing witness
Time taken for parsing witness: 0.097334 s
```
=> perf(circom): optimize zkey wtns reading

.github/workflows/ci.yml, Cargo.Bazel.lock, Cargo.lock, WORKSPACE, benchmark/fft/arkworks/Cargo.toml, benchmark/fft/arkworks/src/lib.rs, benchmark/fft/fft_benchmark.cc, benchmark/fft/fft_benchmark_gpu.cc, benchmark/fft/fft_runner.h, benchmark/poseidon2/plonky3/Cargo.toml, docs/how_to_use/how_to_build.md, tachyon/rs/src/math/finite_fields/mod.rs, tachyon/rs/src/math/geometry/mod.rs, vendors/halo2/Cargo.toml, vendors/sp1/Cargo.toml, vendors/sp1/src/lib.rs
In this PR, `sp1-prover` was updated to version v1.0.1, along with a batch update of the associated packages.
[FYI] Some dependencies of arkworks have changed, but the benchmark results for Poseidon, Poseidon2, FFT and MSM remain unchanged.
=> build: bump up sp1 prover to v1.0.1

.github/workflows/ci.yml
GitHub cache storage is limited to 10GB but it looks like [we can exceed it easily](https://github.com/kroma-network/tachyon/actions/caches) when working on multiple branches.
Exceeding the storage limit may result in unwanted deletion of caches (i.e main branch caches). It even went up to 20GB+ at some point so I had to clean them up with a script. So with this PR, we try to minimize our cache storage usage while keeping build/test time low.
=> ci: reduce cache storage usage

bazel/tachyon_cc.bzl, tachyon/c/zk/plonk/halo2/BUILD.bazel, tachyon/c/zk/plonk/halo2/bn254_prover_unittest.cc, tachyon/math/polynomials/univariate/BUILD.bazel, tachyon/zk/plonk/examples/BUILD.bazel, tachyon/zk/plonk/examples/fibonacci/BUILD.bazel
#498 introduced an `exclusive` tag that caused some tests to run sequentially, which slowed down the test times. This PR improves the situation by limiting the number of threads to 4. This change increases the likelihood of passing the unit tests and reduces the overall test time.
See https://bazel.build/reference/be/common-definitions#common.tags.
=> test: optimize openmp test

bazel/tachyon_cc.bzl, third_party/goldilocks/goldilocks.BUILD
This PR adds `openmp` support for `goldilocks`.
Previously, we used to have a warning when building with openmp.
```
INFO: From Compiling src/goldilocks_base_field.cpp:
external/goldilocks/src/goldilocks_base_field.cpp:72: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
72 | #pragma omp parallel for num_threads(num_threads_copy)
| 
external/goldilocks/src/goldilocks_base_field.cpp:93: warning: ignoring '#pragma omp parallel' [-Wunknown-pragmas]
93 | #pragma omp parallel for num_threads(num_threads_copy)
|
```
=> build: add openmp flags to goldilocks

benchmark/ec/ec_double_benchmark_gpu.cc, tachyon/c/math/elliptic_curves/msm/msm_gpu.h, tachyon/device/gpu/cuda/cub_helper.h, tachyon/device/gpu/gpu_logging.h, tachyon/device/gpu/gpu_memory.cc, tachyon/device/gpu/gpu_memory.h, tachyon/device/gpu/gpu_memory_unittest.cc, tachyon/device/gpu/scoped_event.cc, tachyon/device/gpu/scoped_event.h, tachyon/device/gpu/scoped_mem_pool.cc, tachyon/device/gpu/scoped_mem_pool.h, tachyon/device/gpu/scoped_stream.cc, tachyon/device/gpu/scoped_stream.h, tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bls12_381_g1.cc, tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bls12_381_g2.cc, tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bn254_g1.cc, tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_bn254_g2.cc, tachyon/math/elliptic_curves/msm/variable_base_msm_gpu_unittest.cc, tachyon/math/elliptic_curves/short_weierstrass/affine_point_correctness_gpu_test.cc, tachyon/math/elliptic_curves/short_weierstrass/non_affine_point_correctness_gpu_test.cc, tachyon/math/finite_fields/prime_field_correctness_gpu_test.cc, tachyon/math/finite_fields/prime_field_gpu_unittest.cc, tachyon/math/polynomials/univariate/icicle/icicle_ntt_baby_bear.cc, tachyon/math/polynomials/univariate/icicle/icicle_ntt_bls12_381.cc, tachyon/math/polynomials/univariate/icicle/icicle_ntt_bn254.cc, tachyon/math/test/launch_op_macros.h, third_party/gpus/cuda_configure.bzl, third_party/gpus/rocm_configure.bzl, third_party/node_addon_api/install_node_addon_api.bzl
1. Fixes error messages concerning a function from `Failed to ...()` to `Failed ...()`
2. Renames `GPU_MUST_SUCCESS` to `GPU_MUST_SUCCEED` for better grammar.
=> chore: fix naming and error messages

tachyon/crypto/commitments/fri/two_adic_fri_config.h, tachyon/crypto/commitments/fri/two_adic_fri_pcs.h, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/field_merkle_tree_mmcs.h, tachyon/math/base/semigroups.h, tachyon/math/elliptic_curves/msm/algorithms/icicle/icicle_msm_utils.cc, tachyon/math/finite_fields/prime_field_fallback.h, tachyon/math/finite_fields/prime_field_gpu_debug.h, tachyon/math/matrix/matrix_utils.h, tachyon/math/matrix/matrix_utils_unittest.cc, tachyon/math/polynomials/univariate/evaluations_utils.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain_unittest.cc, tachyon/math/polynomials/univariate/two_adic_subgroup.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain.h, tachyon/math/polynomials/univariate/univariate_evaluation_domain_unittest.cc, tachyon/zk/air/plonky3/base/two_adic_multiplicative_coset.h, tachyon/zk/plonk/halo2/prover.h, tachyon/zk/plonk/halo2/verifier.h, tachyon/zk/plonk/vanishing/vanishing_utils.h
PR #515 introduces an FFT batch benchmark. Initially, the results were not as expected, but after some optimizations, they improved. However, there's still potential for further enhancements. Given that our implementation precomputes twiddles, we would expect even better performance. We need to investigate this further to understand the underlying reasons and explore additional optimizations.
=> perf: optimize fft batch

tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear.h, tachyon/math/finite_fields/finite_field_traits.h, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear.h, tachyon/math/finite_fields/mersenne31/internal/packed_mersenne31.h, tachyon/math/matrix/gmp_num_traits.h, tachyon/math/matrix/prime_field_num_traits.h
If `RequireInitialization` is 1, constructors and destructors are called redundantly.
See https://gitlab.com/libeigen/eigen/-/blob/ab31094/Eigen/src/Core/util/Memory.h#L479-485.
=> perf(math): unset require initialization

tachyon/math/matrix/matrix_utils.h, tachyon/math/polynomials/univariate/naive_batch_fft.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/two_adic_subgroup.h, tachyon/zk/air/plonky3/base/two_adic_multiplicative_coset.h
This PR optimizes `CosetLDEBatch()` and `IFFTBatch()` in a high view.
=> perf(math): optimize radix2 domain

tachyon/crypto/hashes/sponge/poseidon2/poseidon2_plonky3_internal_matrix.h, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx2.cc, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx2.h, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx512.cc, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx512.h, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_neon.cc, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_neon.h, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx2.cc, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx2.h, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx512.cc, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx512.h, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_neon.cc, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_neon.h, tachyon/math/finite_fields/packed_prime_field_base.h, tachyon/math/finite_fields/packed_prime_field_unittest.cc
This PR optimizes packed prime field operations. `RawOne()` should be benchmarked later.
=> perf: optimize packed prime field operations

tachyon/base/compiler_specific.h
This PR fixes broken build with `clang++-15`
=> fix(base): enable building with clang++-15

benchmark/fri/fri_benchmark.cc, benchmark/poseidon2/poseidon2_benchmark_runner.h
Fixes error made in from 76ded8d5a45d191ad831d116a6c9ef3f37d4cde7 which prevented the Fri benchmark from running properly.
=> fix(benchmark): fix faulty fri benchmark

benchmark/fft_batch/fft_batch_runner.h, benchmark/fri/fri_runner.h, tachyon/c/crypto/commitments/fri/two_adic_fri_impl.h, tachyon/c/zk/air/sp1/baby_bear_poseidon2_field_merkle_tree_vec.cc, tachyon/c/zk/air/sp1/baby_bear_poseidon2_two_adic_fri.cc, tachyon/c/zk/air/sp1/baby_bear_poseidon2_two_adic_fri.h, tachyon/c/zk/air/sp1/baby_bear_poseidon2_two_adic_fri_unittest.cc, tachyon/crypto/commitments/fri/prove.h, tachyon/crypto/commitments/fri/two_adic_fri.h, tachyon/crypto/commitments/fri/two_adic_fri_unittest.cc, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/extension_field_merkle_tree_mmcs.h, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/extension_field_merkle_tree_mmcs_unittest.cc, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/field_merkle_tree.h, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/field_merkle_tree_mmcs.h, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/field_merkle_tree_mmcs_unittest.cc, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/field_merkle_tree_unittest.cc, tachyon/crypto/commitments/mixed_matrix_commitment_scheme.h, tachyon/math/matrix/matrix_utils.h, tachyon/math/polynomials/univariate/naive_batch_fft.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain_unittest.cc, vendors/scroll_halo2/src/lib.rs, vendors/sp1/include/baby_bear_poseidon2_two_adic_fri_pcs.h, vendors/sp1/src/baby_bear_poseidon2.rs, vendors/sp1/src/baby_bear_poseidon2_two_adic_fri_pcs.cc, vendors/sp1/src/challenger.rs, vendors/sp1/src/lib.rs, vendors/sp1/src/two_adic_fri_pcs.rs
The commit to matrices are roughly performed in the order below:
`baby_bear_poseidon2::TwoAdicFri::commit()` → `tachyon_sp1_baby_bear_poseidon2_two_adic_fri_allocate_ldes()` -> `tachyon_sp1_baby_bear_poseidon2_two_adic_fri_commit()` → `FieldMerkleTreeMMCS::Commit()` → `Radix2EvaluationDomain::CosetLDEBatch()` → `ExpandInPlaceWithZeroPad()` (This generates the leaves of a merkle tree, which is a vector of the matrix(Low Degree Extension, a.k.a, LDE) which is stored in a `ProverData`).
Previously, LDE was owned by both the C++ and Rust side. In order to prevent the resulting double-free, we add an additional function `std::mem::forget()` on the Rust side. This approach forces us to modify Plonky3 code, but the problem is we can't find where to modify for `0.1.3-succinct` version in Plonky3. …
=> feat: enable using rust allocated ldes

.github/workflows/ci.yml, third_party/goldilocks/goldilocks.BUILD, third_party/hwloc/hwloc.BUILD, third_party/perfetto/perfetto.BUILD, vendors/circom/README.md, vendors/circom/WORKSPACE, vendors/circom/circom.BUILD, vendors/circom/circomlib/build/BUILD.bazel, vendors/circom/circomlib/build/Makefile, vendors/circom/circomlib/build/compile_witness_generator.sh, vendors/circom/circomlib/build/split_tool.cc
This PR introduces a new tool to compile the circuit CPP file generated from the `.circom` file. For large circuits, the generated `CPP` file can get very large making compilation near impossible and even cause OOM errors sometimes. With this tool, the original compilation time which took many hours will be reduced to just few minutes.
=> feat(circom): introduce witness generation tool

benchmark/fft/fft_benchmark.cc, benchmark/fft/fft_benchmark_gpu.cc, benchmark/fft_batch/fft_batch_benchmark.cc, benchmark/fri/fri_benchmark.cc, benchmark/msm/msm_benchmark.cc, benchmark/msm/msm_benchmark_gpu.cc, benchmark/poseidon/poseidon_benchmark.cc, tachyon/crypto/commitments/fri/two_adic_fri.h, tachyon/crypto/commitments/fri/verify.h, tachyon/crypto/commitments/merkle_tree/field_merkle_tree/extension_field_merkle_tree_mmcs.h, tachyon/math/polynomials/univariate/radix2_evaluation_domain.h, tachyon/math/polynomials/univariate/radix2_twiddle_cache.h
Fixes up minor typos and logic errors involved in FRI (+ benchmarks)
=> refac: clean up fri protocol & benchmarks

docker/Dockerfile.circom.jammy, vendors/circom/README.md
This PR adds a Dockerfile for building and running circom binaries.
=> feat: add Dockerfile for circom

tachyon/crypto/commitments/fri/fri_config.h, tachyon/crypto/commitments/fri/simple_fri.h, tachyon/math/base/semigroups.h, tachyon/math/finite_fields/extension_field_base.h
It refactors the code that is used in verfication.
=> refac: refactor `TwoAdicFri` verify

tachyon/crypto/commitments/fri/two_adic_fri.h, tachyon/math/base/semigroups.h, tachyon/math/finite_fields/BUILD.bazel, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx2.cc, tachyon/math/finite_fields/baby_bear/internal/packed_baby_bear_avx2.h, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx2.cc, tachyon/math/finite_fields/koala_bear/internal/packed_koala_bear_avx2.h, tachyon/math/finite_fields/packed_prime_field32_avx2.h, tachyon/math/finite_fields/packed_prime_field32_avx512.h, tachyon/math/finite_fields/packed_prime_field32_neon.h
This optimizes `TwoAdicFri::CreateOpeningProof()` with these 2.
- parallelize copy.
- merge `ReverseMatrixIndexBits()` into one single parallel loop.
In addition, it adopts Plonky3's accelerated x86 simd operations for `PackedBabyBear` and `PackedKoalaBear`.
=> perf(crypto): optimize `TwoAdicFri`

vendors/circom/circomlib/build/compile_witness_generator.sh
When compiling witness generator, sometimes # of parts becomes smaller which results in trying to compile non-overwritten old circuit parts with new parts, causing conflict. This PR fixes it by removing old split parts at the start of every run.
=> fix(circom): delete old parts before splitting
